package main

// Nim target: one module per schema, <input>.nim, with an exported object
// type per schema class, `encode` (-> seq[byte]) and `T.decode` (raises
// DecodeError). Only the Nim standard library is used. See docs/nim.md.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func init() { registerGenerator(genNim, "nim") }

var nimKeywords = map[string]bool{
	"addr": true, "and": true, "as": true, "asm": true, "bind": true, "block": true, "break": true,
	"case": true, "cast": true, "concept": true, "const": true, "continue": true, "converter": true,
	"defer": true, "discard": true, "distinct": true, "div": true, "do": true, "elif": true,
	"else": true, "end": true, "enum": true, "except": true, "export": true, "finally": true,
	"for": true, "from": true, "func": true, "if": true, "import": true, "in": true, "include": true,
	"interface": true, "is": true, "isnot": true, "iterator": true, "let": true, "macro": true,
	"method": true, "mixin": true, "mod": true, "nil": true, "not": true, "notin": true,
	"object": true, "of": true, "or": true, "out": true, "proc": true, "ptr": true, "raise": true,
	"ref": true, "return": true, "shl": true, "shr": true, "static": true, "template": true,
	"try": true, "tuple": true, "type": true, "using": true, "var": true, "when": true,
	"while": true, "xor": true, "yield": true,
}

var nimReserved = map[string]bool{"DecodeError": true, "BpReader": true, "SchemaVersion": true}

func nimScalar(t string) (typ, method string, ok bool) {
	switch t {
	case "int":
		return "int32", "Int", true
	case "long":
		return "int64", "Long", true
	case "float":
		return "float32", "Float", true
	case "double":
		return "float64", "Double", true
	case "bool":
		return "bool", "Bool", true
	case "string":
		return "string", "String", true
	}
	return "", "", false
}

func nimTypeName(n string) string { return crystalTypeName(n) }

// nimFieldName maps snake_case schema names to Nim's camelCase ("i_min" ->
// "iMin"). Nim is style-insensitive, so the two spell the same identifier
// anyway; camelCase is just the conventional spelling.
func nimFieldName(n string) string {
	parts := strings.Split(n, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if b.Len() == 0 {
			b.WriteString(strings.ToLower(p[:1]) + p[1:])
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	s := b.String()
	if s == "" || (s[0] >= '0' && s[0] <= '9') {
		s = "f" + s
	}
	return s
}

// nimObjField is the name of a generated object field. A field named like the
// generated procs would hide them in method-call syntax (o.encode()), so it
// gets a "Field" suffix.
func nimObjField(n string) string {
	s := nimFieldName(n)
	if norm := nimNormalize(s); norm == "encode" || norm == "decode" {
		s += "Field"
	}
	return nimIdent(s)
}

// nimIdent quotes keywords with backticks.
func nimIdent(n string) string {
	if nimKeywords[strings.ToLower(strings.ReplaceAll(n, "_", ""))] {
		return "`" + n + "`"
	}
	return n
}

// nimNormalize is Nim's identifier equality: first char exact, rest
// case- and underscore-insensitive.
func nimNormalize(n string) string {
	if n == "" {
		return n
	}
	return n[:1] + strings.ToLower(strings.ReplaceAll(n[1:], "_", ""))
}

func nimModuleName(stem string) string {
	var b strings.Builder
	for _, r := range stem {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	s := strings.Trim(b.String(), "_")
	for strings.Contains(s, "__") {
		s = strings.ReplaceAll(s, "__", "_")
	}
	if s == "" || (s[0] >= '0' && s[0] <= '9') || nimKeywords[s] {
		s = "schema_" + s
	}
	return s
}

func genNim(classes []Class, cfg GeneratorConfig) error {
	for _, c := range classes {
		if nimReserved[nimTypeName(c.Name)] {
			return fmt.Errorf("nim: class name %q collides with a generated runtime name", c.Name)
		}
		seen := map[string]string{}
		for _, f := range c.Fields {
			n := nimNormalize(strings.Trim(nimObjField(f.Name), "`"))
			if prev, dup := seen[n]; dup {
				return fmt.Errorf("nim: fields %s.%s and %s.%s are the same Nim identifier", c.Name, prev, c.Name, f.Name)
			}
			seen[n] = f.Name
		}
	}

	var b strings.Builder
	w := func(format string, a ...interface{}) { fmt.Fprintf(&b, format, a...) }

	w("## Generated by BitPacker from %s.buff (schema version %s). Do not edit.\n", cfg.InputFileName, cfg.Version)
	w("##\n## Wire format: tools/bit-packer/cross_lang_test/edge/README.md\n## API: tools/bit-packer/docs/nim.md\n\n")
	w("import std/unicode\n\n")
	w("const SchemaVersion* = %q ## Written first in every message; checked by `decode`.\n\n", cfg.Version)
	w("type\n")
	w("  DecodeError* = object of CatchableError\n")
	w("    ## Raised by `decode` for a wrong version prefix, truncated or malformed input.\n\n")
	for _, c := range classes {
		w("  %s* = object\n    ## Schema class `%s`.\n", nimTypeName(c.Name), c.Name)
		for _, f := range c.Fields {
			typ, _, ok := nimScalar(f.Type)
			if !ok {
				typ = nimTypeName(f.Type)
			}
			if f.IsArray {
				typ = "seq[" + typ + "]"
			}
			w("    %s*: %s\n", nimObjField(f.Name), typ)
		}
		w("\n")
	}
	b.WriteString(nimRuntime)

	w("\n# ---- forward declarations ----\n")
	for _, c := range classes {
		n := nimTypeName(c.Name)
		w("proc bpWrite(w: var seq[byte], o: %s) {.raises: [].}\n", n)
		w("proc bpRead%s(r: var BpReader): %s {.raises: [DecodeError].}\n", n, n)
	}

	for _, c := range classes {
		n := nimTypeName(c.Name)
		w("\n# ---- %s ----\n\n", n)
		w("proc bpWrite(w: var seq[byte], o: %s) {.raises: [].} =\n", n)
		if len(c.Fields) == 0 {
			w("  discard\n")
		}
		for _, f := range c.Fields {
			fn := nimObjField(f.Name)
			_, m, scalar := nimScalar(f.Type)
			put := func(x string) string {
				if scalar {
					return "w.bpPut" + m + "(" + x + ")"
				}
				return "w.bpWrite(" + x + ")"
			}
			if f.IsArray {
				w("  w.bpPutCount(o.%s.len)\n", fn)
				w("  for e in o.%s: %s\n", fn, put("e"))
			} else {
				w("  %s\n", put("o."+fn))
			}
		}
		w("\nproc bpRead%s(r: var BpReader): %s {.raises: [DecodeError].} =\n", n, n)
		if len(c.Fields) == 0 {
			w("  discard\n")
		}
		for _, f := range c.Fields {
			fn := nimObjField(f.Name)
			typ, m, scalar := nimScalar(f.Type)
			get := "r.bpGet" + m + "()"
			if !scalar {
				typ = nimTypeName(f.Type)
				get = "r.bpRead" + typ + "()"
			}
			if f.IsArray {
				w("  block:\n    let n = r.bpGetCount()\n    result.%s = newSeqOfCap[%s](n)\n", fn, typ)
				w("    for _ in 0 ..< n: result.%s.add %s\n", fn, get)
			} else {
				w("  result.%s = %s\n", fn, get)
			}
		}
		w("\nproc encode*(o: %s): seq[byte] {.raises: [].} =\n", n)
		w("  ## Encodes `o` as a complete, version-prefixed BitPacker message.\n")
		w("  result = newSeqOfCap[byte](64)\n  result.bpPutString(SchemaVersion)\n  result.bpWrite(o)\n")
		w("\nproc decode*(T: typedesc[%s], data: openArray[byte]): %s {.raises: [DecodeError].} =\n", n, n)
		w("  ## Decodes a message produced by `encode`. Raises `DecodeError` on a wrong\n")
		w("  ## version prefix or truncated/malformed input. Trailing bytes are ignored.\n")
		w("  var r = initBpReader(data)\n  r.bpCheckVersion()\n  result = r.bpRead%s()\n", n)
		w("\nproc decode*(T: typedesc[%s], data: string): %s {.raises: [DecodeError].} =\n", n, n)
		w("  ## Same as the `openArray[byte]` overload, for a message held in a string.\n")
		w("  %s.decode(data.toOpenArrayByte(0, data.high))\n", n)
	}

	if err := os.MkdirAll(cfg.OutDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(cfg.OutDir, nimModuleName(cfg.InputFileName)+".nim"), []byte(b.String()), 0644)
}

const nimRuntime = `  BpReader = object
    p: ptr UncheckedArray[byte]
    len, pos: int

# ---- writer ----

proc bpUvarint(w: var seq[byte], v: uint64) {.raises: [].} =
  var v = v
  while v >= 0x80'u64:
    w.add byte((v and 0x7F'u64) or 0x80'u64)
    v = v shr 7
  w.add byte(v)

proc bpPutInt(w: var seq[byte], v: int32) {.raises: [].} =
  let u = cast[uint32](v)
  let sign = if v < 0: high(uint32) else: 0'u32
  w.bpUvarint(uint64((u shl 1) xor sign))

proc bpPutLong(w: var seq[byte], v: int64) {.raises: [].} =
  let u = cast[uint64](v)
  let sign = if v < 0: high(uint64) else: 0'u64
  w.bpUvarint((u shl 1) xor sign)

proc bpFixed(p: float64): int64 {.raises: [].} =
  # Truncates toward zero; NaN -> 0, out of range saturates (as Java does).
  if p != p: 0'i64
  elif p >= 9223372036854775808.0: high(int64)
  elif p <= -9223372036854775808.0: low(int64)
  else: int64(p)

proc bpPutFloat(w: var seq[byte], v: float32) {.raises: [].} =
  # The x10000 product must be the float32 product, as in the Go and Java
  # targets. A float32 x float32 product is exact in float64, so rounding it
  # once to float32 is exactly IEEE single-precision multiplication, whatever
  # precision the C compiler uses for float32 temporaries.
  w.bpPutLong(bpFixed(float64(float32(float64(v) * 10000.0))))

proc bpPutDouble(w: var seq[byte], v: float64) {.raises: [].} =
  w.bpPutLong(bpFixed(v * 10000.0))

proc bpPutBool(w: var seq[byte], v: bool) {.raises: [].} =
  w.add(if v: 1'u8 else: 0'u8)

proc bpPutString(w: var seq[byte], v: string) {.raises: [].} =
  w.bpPutLong(int64(v.len))
  let start = w.len
  w.setLen(start + v.len)
  if v.len > 0:
    copyMem(addr w[start], unsafeAddr v[0], v.len)

proc bpPutCount(w: var seq[byte], n: int) {.raises: [].} =
  doAssert n <= int(high(int32)), "BitPacker: array longer than high(int32)"
  w.bpPutInt(int32(n))

# ---- reader ----

proc initBpReader(data: openArray[byte]): BpReader {.raises: [].} =
  result.len = data.len
  if data.len > 0:
    result.p = cast[ptr UncheckedArray[byte]](unsafeAddr data[0])

proc bpFail(msg: string) {.noreturn, raises: [DecodeError].} =
  raise newException(DecodeError, msg)

proc bpGetByte(r: var BpReader): byte {.raises: [DecodeError].} =
  if r.pos >= r.len: bpFail("unexpected end of input at byte " & $r.pos)
  result = r.p[r.pos]
  inc r.pos

proc bpUvarint(r: var BpReader): uint64 {.raises: [DecodeError].} =
  var shift = 0
  while true:
    let b = r.bpGetByte()
    if shift == 63 and b > 1'u8: bpFail("varint overflows 64 bits")
    result = result or (uint64(b and 0x7F'u8) shl shift)
    if b < 0x80'u8: return
    shift += 7

proc bpGetInt(r: var BpReader): int32 {.raises: [DecodeError].} =
  let u = r.bpUvarint()
  if u > uint64(high(uint32)): bpFail("int varint overflows 32 bits")
  let v = uint32(u)
  cast[int32]((v shr 1) xor (0'u32 - (v and 1'u32)))

proc bpGetLong(r: var BpReader): int64 {.raises: [DecodeError].} =
  let u = r.bpUvarint()
  cast[int64]((u shr 1) xor (0'u64 - (u and 1'u64)))

proc bpGetFloat(r: var BpReader): float32 {.raises: [DecodeError].} =
  # float32(n) / 10000 in single precision, as Go/Java decode. The float64
  # quotient rounded once to float32 equals the IEEE float32 quotient.
  let n = r.bpGetLong()
  float32(float64(float32(n)) / 10000.0)

proc bpGetDouble(r: var BpReader): float64 {.raises: [DecodeError].} =
  float64(r.bpGetLong()) / 10000.0

proc bpGetBool(r: var BpReader): bool {.raises: [DecodeError].} =
  r.bpGetByte() != 0'u8

proc bpGetString(r: var BpReader): string {.raises: [DecodeError].} =
  let n = r.bpGetLong()
  if n < 0 or n > int64(r.len - r.pos):
    bpFail("bad string length " & $n & " at byte " & $r.pos)
  result = newString(int(n))
  if n > 0:
    copyMem(addr result[0], addr r.p[r.pos], int(n))
  r.pos += int(n)
  if validateUtf8(result) != -1: bpFail("string is not valid UTF-8")

proc bpGetCount(r: var BpReader): int {.raises: [DecodeError].} =
  # Every element takes at least one byte, so a count larger than the
  # remaining input is rejected before anything is allocated.
  let n = r.bpGetInt()
  if n < 0 or int(n) > r.len - r.pos:
    bpFail("bad array length " & $n & " at byte " & $r.pos)
  int(n)

proc bpCheckVersion(r: var BpReader) {.raises: [DecodeError].} =
  let v = r.bpGetString()
  if v != SchemaVersion:
    bpFail("version mismatch: expected " & SchemaVersion & ", got " & v)
`
