package main

// Elixir target: `--lang elixir` (alias `ex`).
//
// Writes <schema>.ex with one module per class, named
// <SchemaPascal>.<Class> (e.g. BenchComplex.WorldState), each with a
// defstruct, @type t, encode/1 -> binary() and decode/1 ->
// {:ok, struct} | {:error, reason}, plus a shared <SchemaPascal>.BitPacker
// wire module. See docs/elixir.md.

import (
	"fmt"
	"strings"
	"unicode"
)

func init() { registerGenerator(genElixir, "elixir", "ex") }

// elixirKey renders a struct key in keyword syntax ("name:"), quoting keys
// that are not plain identifiers.
func elixirKey(s string) string {
	plain := s != "" && (s[0] >= 'a' && s[0] <= 'z' || s[0] == '_')
	for _, c := range s {
		if !(c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '_') {
			plain = false
		}
	}
	if plain {
		return s + ":"
	}
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `":`
}

func elixirModName(s string) string {
	p := funclangPascal(s)
	r := []rune(p)
	if !unicode.IsLetter(r[0]) {
		p = "M" + p
	}
	return p
}

func elixirDefault(f Field) string {
	if f.IsArray {
		return "[]"
	}
	switch f.Type {
	case "int", "long":
		return "0"
	case "float", "double":
		return "0.0"
	case "bool":
		return "false"
	case "string":
		return `""`
	}
	return "nil"
}

func elixirSpec(ns string, f Field) string {
	var t string
	switch f.Type {
	case "int":
		t = "-2_147_483_648..2_147_483_647"
	case "long":
		t = "integer()"
	case "float", "double":
		t = "float()"
	case "bool":
		t = "boolean()"
	case "string":
		t = "String.t()"
	default:
		t = ns + "." + elixirModName(f.Type) + ".t()"
	}
	if f.IsArray {
		return "[" + t + "]"
	}
	if !funclangIsScalar(f.Type) {
		return t + " | nil"
	}
	return t
}

func genElixir(classes []Class, cfg GeneratorConfig) error {
	if err := funclangCheck(classes); err != nil {
		return err
	}
	ns := elixirModName(cfg.InputFileName)
	byName := funclangByName(classes)
	bp := ns + ".BitPacker"

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by BitPacker from %s.buff (schema version %s). Do not edit.\n\n", cfg.InputFileName, cfg.Version)
	b.WriteString(strings.ReplaceAll(strings.ReplaceAll(elixirRuntime, "__BP__", bp), "__VERSION__", cfg.Version))

	for _, c := range classes {
		mod := ns + "." + elixirModName(c.Name)
		fmt.Fprintf(&b, "\ndefmodule %s do\n", mod)
		fmt.Fprintf(&b, "  @moduledoc \"BitPacker class `%s` (schema `%s.buff`, version %s).\"\n\n", c.Name, cfg.InputFileName, cfg.Version)
		fmt.Fprintf(&b, "  alias %s, as: BP\n\n", bp)
		if len(c.Fields) == 0 {
			b.WriteString("  defstruct []\n\n  @type t :: %__MODULE__{}\n\n")
		} else {
			b.WriteString("  defstruct ")
			for i, f := range c.Fields {
				if i > 0 {
					b.WriteString(",\n            ")
				}
				fmt.Fprintf(&b, "%s %s", elixirKey(f.Name), elixirDefault(f))
			}
			b.WriteString("\n\n  @type t :: %__MODULE__{\n")
			for i, f := range c.Fields {
				sep := ","
				if i == len(c.Fields)-1 {
					sep = ""
				}
				fmt.Fprintf(&b, "          %s %s%s\n", elixirKey(f.Name), elixirSpec(ns, f), sep)
			}
			b.WriteString("        }\n\n")
		}
		b.WriteString(`  @doc """
  Encodes the struct as a version-prefixed BitPacker message.

  Raises ArgumentError for a value the wire cannot carry (a non-integer
  in an int field, a float outside the fixed-point range, ...). Integers
  wider than the field wrap like a two's-complement cast.
  """
  @spec encode(t()) :: binary()
  def encode(%__MODULE__{} = value), do: BP.encode_message(value, &encode_body/1)

  @doc "Decodes a version-prefixed message. Bytes after the message are ignored."
  @spec decode(binary()) :: {:ok, t()} | {:error, term()}
  def decode(data), do: BP.decode_message(data, &decode_body/1)

  @doc false
  def encode_body(nil), do: encode_body(%__MODULE__{})

`)
		if len(c.Fields) == 0 {
			b.WriteString("  def encode_body(%__MODULE__{}), do: []\n\n")
		} else {
			b.WriteString("  def encode_body(%__MODULE__{")
			for i, f := range c.Fields {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%s f%d", elixirKey(f.Name), i+1)
			}
			b.WriteString("}) do\n    [\n")
			for i, f := range c.Fields {
				sep := ","
				if i == len(c.Fields)-1 {
					sep = ""
				}
				fmt.Fprintf(&b, "      %s%s\n", elixirPut(ns, f, fmt.Sprintf("f%d", i+1)), sep)
			}
			b.WriteString("    ]\n  end\n\n")
		}
		b.WriteString("  @doc false\n  def decode_body(b0) do\n")
		for i, f := range c.Fields {
			min := 0
			if funclangMinOneByte(f.Type, byName, map[string]bool{}) {
				min = 1
			}
			fmt.Fprintf(&b, "    {f%d, b%d} = %s\n", i+1, i+1, elixirGet(ns, f, fmt.Sprintf("b%d", i), min))
		}
		b.WriteString("    {%__MODULE__{")
		for i, f := range c.Fields {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%s f%d", elixirKey(f.Name), i+1)
		}
		fmt.Fprintf(&b, "}, b%d}\n  end\nend\n", len(c.Fields))
	}
	return funclangWrite(cfg.OutDir, funclangSnake(cfg.InputFileName)+".ex", b.String())
}

func elixirPutFun(ns, t string) string {
	if funclangIsScalar(t) {
		return "&BP.put_" + t + "/1"
	}
	return "&" + ns + "." + elixirModName(t) + ".encode_body/1"
}

func elixirPut(ns string, f Field, v string) string {
	if f.IsArray {
		return fmt.Sprintf("BP.put_array(%s, %s)", v, elixirPutFun(ns, f.Type))
	}
	if funclangIsScalar(f.Type) {
		return fmt.Sprintf("BP.put_%s(%s)", f.Type, v)
	}
	return fmt.Sprintf("%s.%s.encode_body(%s)", ns, elixirModName(f.Type), v)
}

func elixirGet(ns string, f Field, b string, min int) string {
	if f.IsArray {
		fn := "&BP.get_" + f.Type + "/1"
		if !funclangIsScalar(f.Type) {
			fn = "&" + ns + "." + elixirModName(f.Type) + ".decode_body/1"
		}
		return fmt.Sprintf("BP.get_array(%s, %s, %d)", b, fn, min)
	}
	if funclangIsScalar(f.Type) {
		return fmt.Sprintf("BP.get_%s(%s)", f.Type, b)
	}
	return fmt.Sprintf("%s.%s.decode_body(%s)", ns, elixirModName(f.Type), b)
}

const elixirRuntime = `defmodule __BP__ do
  @moduledoc false
  # Wire runtime shared by the generated modules (cross_lang_test/edge/README.md).
  import Bitwise

  @version "__VERSION__"
  @m32 0xFFFFFFFF
  @m64 0xFFFFFFFFFFFFFFFF

  @doc false
  def version, do: @version

  def encode_message(value, body) do
    IO.iodata_to_binary([put_string(@version), body.(value)])
  catch
    {:bitpacker, reason} -> raise ArgumentError, "BitPacker encode: #{inspect(reason)}"
  end

  def decode_message(data, body) when is_binary(data) do
    {v, rest} = get_string(data)
    if v != @version, do: fail({:version_mismatch, @version, v})
    {value, _trailing} = body.(rest)
    {:ok, value}
  catch
    {:bitpacker, reason} -> {:error, reason}
  end

  def decode_message(_, _), do: {:error, :badarg}

  defp fail(reason), do: throw({:bitpacker, reason})

  # ---- encoding (returns iodata) ----

  defp uvarint(n) when n < 128, do: [n]
  defp uvarint(n), do: [bor(band(n, 127), 128) | uvarint(bsr(n, 7))]

  # Two's-complement wrap of any integer into bits, then zigzag.
  defp zigzag(v, bits, mask) do
    w = band(v, mask)
    s = if bsr(w, bits - 1) == 0, do: w, else: w - (mask + 1)
    band(bxor(bsl(s, 1), bsr(s, bits - 1)), mask)
  end

  def put_int(v) when is_integer(v), do: uvarint(zigzag(v, 32, @m32))
  def put_int(v), do: fail({:not_an_integer, v})

  def put_long(v) when is_integer(v), do: uvarint(zigzag(v, 64, @m64))
  def put_long(v), do: fail({:not_an_integer, v})

  # Round to the nearest float32; fails outside the float32 range.
  defp f32(x) do
    case <<x::float-32>> do
      <<y::float-32>> -> y
      _ -> fail({:float32_out_of_range, x})
    end
  end

  # float fields: the x10000 is done in single precision like the float32
  # targets: trunc(float32(float32(v) * 10000)).
  def put_float(v) when is_number(v) do
    f = f32(to_float(v, :float32_out_of_range))
    put_fixed(f32(f * 10000.0))
  end

  def put_float(v), do: fail({:not_a_number, v})

  def put_double(v) when is_number(v) do
    put_fixed(to_float(v, :double_out_of_range) * 10000.0)
  end

  def put_double(v), do: fail({:not_a_number, v})

  # A bignum too large for a double, or a double whose x10000 overflows.
  defp to_float(v, why) do
    f = v * 1.0
    _ = f * 10000.0
    f
  rescue
    ArithmeticError -> fail({why, v})
  end

  defp put_fixed(s) do
    t = trunc(s)

    if t >= -0x8000000000000000 and t <= 0x7FFFFFFFFFFFFFFF,
      do: put_long(t),
      else: fail({:fixed_point_out_of_range, s})
  end

  def put_bool(true), do: [1]
  def put_bool(false), do: [0]
  def put_bool(v), do: fail({:not_a_boolean, v})

  def put_string(s) when is_binary(s), do: [put_long(byte_size(s)), s]
  def put_string(s), do: fail({:not_a_string, s})

  def put_array(l, put) when is_list(l), do: [put_int(length(l)) | Enum.map(l, put)]
  def put_array(l, _), do: fail({:not_a_list, l})

  # ---- decoding: binary -> {value, rest} ----

  defp get_uvarint(b), do: get_uvarint(b, 0, 0)

  defp get_uvarint(<<1::1, v::7, rest::binary>>, shift, acc) when shift < 63,
    do: get_uvarint(rest, shift + 7, bor(acc, bsl(v, shift)))

  defp get_uvarint(<<0::1, v::7, rest::binary>>, shift, acc),
    do: {band(bor(acc, bsl(v, shift)), @m64), rest}

  defp get_uvarint(<<_, _::binary>>, _, _), do: fail(:varint_too_long)
  defp get_uvarint(<<>>, _, _), do: fail(:truncated)

  def get_int(b) do
    {u, r} = get_uvarint(b)
    z = band(u, @m32)
    {bxor(bsr(z, 1), -band(z, 1)), r}
  end

  def get_long(b) do
    {z, r} = get_uvarint(b)
    {bxor(bsr(z, 1), -band(z, 1)), r}
  end

  # Correctly rounded int64 -> float32 (a double would round twice above 2^53).
  defp int_to_f32(n) when n < 1 <<< 53 and n > -(1 <<< 53), do: f32(n * 1.0)

  defp int_to_f32(n) do
    a = abs(n)
    y = bor(bsr(a, 11), if(band(a, 2047) == 0, do: 0, else: 1))
    f = f32(y * 2048.0)
    if n < 0, do: -f, else: f
  end

  def get_float(b) do
    {n, r} = get_long(b)
    {f32(int_to_f32(n) / 10000.0), r}
  end

  def get_double(b) do
    {n, r} = get_long(b)
    {n / 10000.0, r}
  end

  def get_bool(<<0, r::binary>>), do: {false, r}
  def get_bool(<<_, r::binary>>), do: {true, r}
  def get_bool(<<>>), do: fail(:truncated)

  def get_string(b) do
    {len, r} = get_long(b)
    if len < 0, do: fail({:negative_length, len})

    case r do
      <<s::binary-size(len), r2::binary>> ->
        if String.valid?(s), do: {:binary.copy(s), r2}, else: fail(:invalid_utf8)

      _ ->
        fail(:truncated)
    end
  end

  # min is 1 when every element takes at least one byte, so a count larger
  # than the bytes left is rejected before any work is done.
  def get_array(b, get, min) do
    {n, r} = get_int(b)
    if n < 0, do: fail({:negative_length, n})
    if min == 1 and n > byte_size(r), do: fail(:truncated)
    get_n(n, r, get, [])
  end

  defp get_n(0, r, _, acc), do: {:lists.reverse(acc), r}

  defp get_n(n, b, get, acc) do
    {v, r} = get.(b)
    get_n(n - 1, r, get, [v | acc])
  end
end
`
