package main

// Kotlin/JVM target: `--lang kotlin` (alias `kt`). Writes <schema>.kt in
// package --package (default "generated"): one data class per schema class,
// with encode(): ByteArray and companion decode(ByteArray) that THROWS
// BitPackerException (wrap with runCatching { } for a Result). Uses only the
// Kotlin stdlib and java.nio. See docs/kotlin.md.

import (
	"fmt"
	"strings"
)

func init() { registerGenerator(genKotlin, "kotlin", "kt") }

var kotlinKeywords = map[string]bool{
	"as": true, "break": true, "class": true, "continue": true, "do": true, "else": true,
	"false": true, "for": true, "fun": true, "if": true, "in": true, "interface": true,
	"is": true, "null": true, "object": true, "package": true, "return": true, "super": true,
	"this": true, "throw": true, "true": true, "try": true, "typealias": true, "typeof": true,
	"val": true, "var": true, "when": true, "while": true,
}

func kotlinField(name string) string {
	n := polyglotCamel(name)
	if kotlinKeywords[n] {
		return "`" + n + "`"
	}
	return n
}

func kotlinScalar(t string) string {
	switch t {
	case "int":
		return "Int"
	case "long":
		return "Long"
	case "float":
		return "Float"
	case "double":
		return "Double"
	case "bool":
		return "Boolean"
	case "string":
		return "String"
	}
	return t
}

func kotlinType(f Field) string {
	if f.IsArray {
		return "List<" + kotlinScalar(f.Type) + ">"
	}
	return kotlinScalar(f.Type)
}

func kotlinDefault(f Field) string {
	if f.IsArray {
		return "emptyList()"
	}
	switch f.Type {
	case "int":
		return "0"
	case "long":
		return "0L"
	case "float":
		return "0.0f"
	case "double":
		return "0.0"
	case "bool":
		return "false"
	case "string":
		return `""`
	}
	return f.Type + "()"
}

func kotlinRead(t string) string {
	if polyglotIsScalar(t) {
		return "r." + t + "()"
	}
	return t + ".readFrom(r)"
}

func kotlinWrite(expr, t string) string {
	if polyglotIsScalar(t) {
		return "w." + t + "(" + expr + ")"
	}
	return expr + ".writeTo(w)"
}

func genKotlin(classes []Class, cfg GeneratorConfig) error {
	if err := polyglotValidate("kotlin", classes, kotlinField); err != nil {
		return err
	}
	if err := polyglotCheckClassNames("kotlin", classes, "BitPackerWriter", "BitPackerReader", "BitPackerException",
		"VERSION", "String", "Int", "Long", "Float", "Double", "Boolean", "List", "ArrayList", "ByteArray",
		"Any", "Unit", "Nothing", "Exception", "Byte", "Char"); err != nil {
		return err
	}
	p := &polyglotLines{unit: "    "}
	p.line("// Generated by BitPacker from %s.buff (schema version %s). Do not edit.", cfg.InputFileName, cfg.Version)
	p.line("package %s", cfg.PackageName)
	p.line("")
	p.line("import java.nio.ByteBuffer")
	p.line("import java.nio.charset.CharacterCodingException")
	p.line("import java.nio.charset.CodingErrorAction")
	p.line("")
	p.line("/** The schema version every encoded message starts with. */")
	p.line("public const val VERSION: String = %s", polyglotQuote(cfg.Version))
	p.raw(kotlinRuntime)
	for _, c := range classes {
		kotlinClass(p, c)
	}
	return polyglotWrite(cfg, cfg.InputFileName+".kt", p.String())
}

func kotlinClass(p *polyglotLines, c Class) {
	n := c.Name
	p.line("")
	if len(c.Fields) == 0 {
		p.line("public class %s {", n)
		p.in()
		p.line("override fun equals(other: Any?): Boolean = other is %s", n)
		p.line("override fun hashCode(): Int = 0")
		p.line("override fun toString(): String = \"%s()\"", n)
	} else {
		p.line("public data class %s(", n)
		p.in()
		for _, f := range c.Fields {
			p.line("val %s: %s = %s,", kotlinField(f.Name), kotlinType(f), kotlinDefault(f))
		}
		p.out()
		p.line(") {")
		p.in()
	}
	p.line("/**")
	p.line(" * Encodes this value as a version-prefixed BitPacker message.")
	p.line(" * @throws IllegalArgumentException if a float/double field is NaN, infinite or out of fixed-point range")
	p.line(" */")
	p.line("public fun encode(): ByteArray {")
	p.line("    val w = BitPackerWriter()")
	p.line("    w.string(VERSION)")
	p.line("    writeTo(w)")
	p.line("    return w.toByteArray()")
	p.line("}")
	p.line("")
	p.line("internal fun writeTo(w: BitPackerWriter) {")
	p.in()
	for _, f := range c.Fields {
		fn := "this." + kotlinField(f.Name)
		if f.IsArray {
			p.line("w.int(%s.size)", fn)
			p.line("for (x in %s) %s", fn, kotlinWrite("x", f.Type))
		} else {
			p.line("%s", kotlinWrite(fn, f.Type))
		}
	}
	p.out()
	p.line("}")
	p.line("")
	p.line("public companion object {")
	p.in()
	p.line("/** Decodes a version-prefixed message; throws BitPackerException on a version mismatch or malformed/truncated input. */")
	p.line("@JvmStatic")
	p.line("@Throws(BitPackerException::class)")
	p.line("public fun decode(data: ByteArray): %s {", n)
	p.line("    val r = BitPackerReader(data)")
	p.line("    r.version(VERSION)")
	p.line("    return readFrom(r)")
	p.line("}")
	p.line("")
	p.line("internal fun readFrom(r: BitPackerReader): %s {", n)
	p.in()
	p.line("r.enter()")
	var args []string
	for i, f := range c.Fields {
		if f.IsArray {
			p.line("val n%d = r.count()", i)
			p.line("val f%d = ArrayList<%s>(n%d)", i, kotlinScalar(f.Type), i)
			p.line("repeat(n%d) { f%d.add(%s) }", i, i, kotlinRead(f.Type))
		} else {
			p.line("val f%d = %s", i, kotlinRead(f.Type))
		}
		args = append(args, fmt.Sprintf("%s = f%d", kotlinField(f.Name), i))
	}
	p.line("r.leave()")
	p.line("return %s(%s)", n, strings.Join(args, ", "))
	p.out()
	p.line("}")
	p.out()
	p.line("}")
	p.out()
	p.line("}")
}

const kotlinRuntime = `
/** Thrown by decode() on a version mismatch or malformed/truncated input. */
public class BitPackerException(message: String) : Exception(message)

internal class BitPackerWriter {
    private var buf = ByteArray(256)
    private var pos = 0

    private fun reserve(n: Int) {
        if (pos + n <= buf.size) return
        var cap = buf.size * 2
        while (cap < pos + n) cap *= 2
        buf = buf.copyOf(cap)
    }

    /** Unsigned LEB128 of the 64 bits of u. */
    private fun uvarint(u0: Long) {
        reserve(10)
        var u = u0
        while (u and 0x7FL.inv() != 0L) {
            buf[pos++] = ((u and 0x7FL) or 0x80L).toByte()
            u = u ushr 7
        }
        buf[pos++] = u.toByte()
    }

    fun int(v: Int) = uvarint(((v shl 1) xor (v shr 31)).toLong() and 0xFFFFFFFFL)

    fun long(v: Long) = uvarint((v shl 1) xor (v shr 63))

    /** Fixed point: scaled is v * 10000 in the field's precision, truncated
     *  toward zero. NaN, infinities and out-of-range products are rejected. */
    private fun fixed(scaled: Double, kind: String, v: Any) {
        require(scaled >= -9.223372036854775808E18 && scaled < 9.223372036854775808E18) {
            "BitPacker: $kind value $v is NaN, infinite or too large for fixed point (v * 10000 must fit in a Long)"
        }
        long(scaled.toLong())
    }

    /** v * 10000 in single precision (float32), exactly as the Go/Java targets. */
    fun float(v: Float) = fixed((v * 10000.0f).toDouble(), "float", v)

    fun double(v: Double) = fixed(v * 10000.0, "double", v)

    fun bool(v: Boolean) {
        reserve(1)
        buf[pos++] = if (v) 1 else 0
    }

    fun string(v: String) {
        val b = v.toByteArray(Charsets.UTF_8)
        long(b.size.toLong())
        reserve(b.size)
        b.copyInto(buf, pos)
        pos += b.size
    }

    fun toByteArray(): ByteArray = buf.copyOf(pos)
}

internal class BitPackerReader(private val buf: ByteArray) {
    private var pos = 0
    private var depth = 0
    private val utf8 = Charsets.UTF_8.newDecoder()
        .onMalformedInput(CodingErrorAction.REPORT)
        .onUnmappableCharacter(CodingErrorAction.REPORT)

    private fun fail(msg: String): Nothing = throw BitPackerException("$msg at byte $pos")

    private fun byte(): Int {
        if (pos >= buf.size) fail("truncated input")
        return buf[pos++].toInt() and 0xFF
    }

    /** Unsigned LEB128, at most 10 bytes / 64 bits. */
    private fun uvarint(): Long {
        var result = 0L
        var shift = 0
        while (true) {
            val b = byte()
            if (shift == 63 && b > 1) fail("varint overflows 64 bits")
            result = result or ((b and 0x7F).toLong() shl shift)
            if (b < 0x80) return result
            shift += 7
        }
    }

    fun long(): Long {
        val u = uvarint()
        return (u ushr 1) xor -(u and 1L)
    }

    fun int(): Int {
        val u = uvarint()
        if (u < 0L || u > 0xFFFFFFFFL) fail("int out of 32-bit range")
        val x = u.toInt()
        return (x ushr 1) xor -(x and 1)
    }

    fun float(): Float = long().toFloat() / 10000.0f

    fun double(): Double = long().toDouble() / 10000.0

    fun bool(): Boolean = byte() != 0

    /** Array element count: must be >= 0 and no larger than the bytes left. */
    fun count(): Int {
        val n = int()
        if (n < 0 || n > buf.size - pos) fail("bad array length $n")
        return n
    }

    fun string(): String {
        val n = long()
        if (n < 0L || n > (buf.size - pos).toLong()) fail("bad string length $n")
        val len = n.toInt()
        val s = try {
            utf8.decode(ByteBuffer.wrap(buf, pos, len)).toString()
        } catch (e: CharacterCodingException) {
            fail("invalid UTF-8")
        }
        pos += len
        return s
    }

    fun version(expected: String) {
        val v = string()
        if (v != expected) throw BitPackerException("version mismatch: expected $expected, got $v")
    }

    fun enter() {
        if (++depth > 512) fail("nesting deeper than 512")
    }

    fun leave() {
        depth--
    }
}
`
