package main

// F# target: `--lang fsharp` (alias `fs`). Writes <schema>.fs in namespace
// --package (default "generated", PascalCased per segment: "Generated"):
// one immutable record per schema class (arrays are F# lists), with
// member Encode(): byte[] and static Decode(byte[]): Result<'T, string>.
// .NET base library only. See docs/fsharp.md.

import (
	"fmt"
	"strings"
)

func init() { registerGenerator(genFSharp, "fsharp", "fs") }

var fsharpMembers = map[string]bool{
	"Encode": true, "Decode": true, "Default": true, "WriteTo": true, "ReadFrom": true,
	"Equals": true, "GetHashCode": true, "ToString": true, "GetType": true, "CompareTo": true,
}

// F# keywords are lower case; a PascalCased field only needs care when it
// starts with a non-letter, which polyglotPascal leaves alone.
var fsharpKeywords = map[string]bool{
	"abstract": true, "and": true, "as": true, "assert": true, "base": true, "begin": true,
	"class": true, "default": true, "delegate": true, "do": true, "done": true, "downcast": true,
	"downto": true, "elif": true, "else": true, "end": true, "exception": true, "extern": true,
	"false": true, "finally": true, "fixed": true, "for": true, "fun": true, "function": true,
	"global": true, "if": true, "in": true, "inherit": true, "inline": true, "interface": true,
	"internal": true, "lazy": true, "let": true, "match": true, "member": true, "module": true,
	"mutable": true, "namespace": true, "new": true, "not": true, "null": true, "of": true,
	"open": true, "or": true, "override": true, "private": true, "public": true, "rec": true,
	"return": true, "select": true, "sig": true, "static": true, "struct": true, "then": true,
	"to": true, "true": true, "try": true, "type": true, "upcast": true, "use": true, "val": true,
	"void": true, "when": true, "while": true, "with": true, "yield": true, "const": true,
}

func fsharpField(name string) string {
	n := polyglotPascal(name)
	if fsharpMembers[n] {
		n += "_"
	}
	if fsharpKeywords[n] {
		return "``" + n + "``"
	}
	return n
}

func fsharpNamespace(pkg string) string {
	parts := strings.Split(pkg, ".")
	for i, s := range parts {
		parts[i] = polyglotPascal(s)
	}
	return strings.Join(parts, ".")
}

func fsharpScalar(t string) string {
	switch t {
	case "int":
		return "int32"
	case "long":
		return "int64"
	case "float":
		return "float32"
	case "double":
		return "float"
	case "bool":
		return "bool"
	case "string":
		return "string"
	}
	return t
}

func fsharpType(f Field) string {
	if f.IsArray {
		return fsharpScalar(f.Type) + " list"
	}
	return fsharpScalar(f.Type)
}

func fsharpDefault(f Field) string {
	if f.IsArray {
		return "[]"
	}
	switch f.Type {
	case "int":
		return "0"
	case "long":
		return "0L"
	case "float":
		return "0.0f"
	case "double":
		return "0.0"
	case "bool":
		return "false"
	case "string":
		return `""`
	}
	return f.Type + ".Default"
}

func fsharpRead(t string) string {
	if polyglotIsScalar(t) {
		return "r." + polyglotPascal(t) + "()"
	}
	return t + ".ReadFrom(r)"
}

func fsharpWrite(expr, t string) string {
	if polyglotIsScalar(t) {
		return "w." + polyglotPascal(t) + "(" + expr + ")"
	}
	return t + ".WriteTo(w, " + expr + ")"
}

func genFSharp(classes []Class, cfg GeneratorConfig) error {
	if err := polyglotValidate("fsharp", classes, fsharpField); err != nil {
		return err
	}
	if err := polyglotCheckClassNames("fsharp", classes, "BitPacker", "BitPackerWriter", "BitPackerReader",
		"BitPackerException", "Result", "Ok", "Error", "List", "Array", "String", "Int32", "Int64",
		"Double", "Single", "Boolean", "Byte", "Exception", "Buffer", "Math", "Object", "Text"); err != nil {
		return err
	}
	p := &polyglotLines{unit: "    "}
	p.line("// Generated by BitPacker from %s.buff (schema version %s). Do not edit.", cfg.InputFileName, cfg.Version)
	p.line("namespace %s", fsharpNamespace(cfg.PackageName))
	p.line("")
	p.line("open System")
	p.line("open System.Text")
	p.line("")
	p.line("[<RequireQualifiedAccess>]")
	p.line("module BitPacker =")
	p.line("    /// The schema version every encoded message starts with.")
	p.line("    [<Literal>]")
	p.line("    let Version = %s", polyglotQuote(cfg.Version))
	p.raw(fsharpRuntime)
	for i, c := range classes {
		fsharpClass(p, c, i == 0)
	}
	return polyglotWrite(cfg, cfg.InputFileName+".fs", p.String())
}

func fsharpClass(p *polyglotLines, c Class, first bool) {
	n := c.Name
	kw := "and"
	if first {
		kw = "type"
	}
	p.line("")
	if len(c.Fields) == 0 {
		p.line("%s %s =", kw, n)
		p.in()
		p.line("| %s", n)
		p.line("/// The value with every field at its zero value.")
		p.line("static member Default : %s = %s", n, n)
	} else {
		p.line("%s %s =", kw, n)
		p.in()
		for i, f := range c.Fields {
			open := "  "
			if i == 0 {
				open = "{ "
			}
			close := ""
			if i == len(c.Fields)-1 {
				close = " }"
			}
			p.line("%s%s: %s%s", open, fsharpField(f.Name), fsharpType(f), close)
		}
		p.line("")
		p.line("/// The value with every field at its zero value; build others with { %s.Default with ... }.", n)
		var inits []string
		for _, f := range c.Fields {
			inits = append(inits, fmt.Sprintf("%s = %s", fsharpField(f.Name), fsharpDefault(f)))
		}
		p.line("static member Default : %s = { %s }", n, strings.Join(inits, "; "))
	}
	p.line("")
	p.line("/// Encodes this value as a version-prefixed BitPacker message. Raises ArgumentException")
	p.line("/// if a float/double field is NaN, infinite or out of fixed-point range.")
	p.line("member this.Encode() : byte[] =")
	p.line("    let w = BitPackerWriter()")
	p.line("    w.String(BitPacker.Version)")
	p.line("    %s.WriteTo(w, this)", n)
	p.line("    w.ToArray()")
	p.line("")
	p.line("/// Decodes a version-prefixed message: Error reason on a version mismatch or malformed/truncated input.")
	p.line("static member Decode(data: byte[]) : Result<%s, string> =", n)
	p.line("    try")
	p.line("        let r = BitPackerReader(data)")
	p.line("        r.Version(BitPacker.Version)")
	p.line("        Ok(%s.ReadFrom(r))", n)
	p.line("    with :? BitPackerException as e ->")
	p.line("        Error e.Message")
	p.line("")
	p.line("static member internal WriteTo(w: BitPackerWriter, v: %s) : unit =", n)
	p.in()
	for _, f := range c.Fields {
		fn := "v." + fsharpField(f.Name)
		if f.IsArray {
			p.line("w.Int(List.length %s)", fn)
			p.line("for x in %s do %s", fn, fsharpWrite("x", f.Type))
		} else {
			p.line("%s", fsharpWrite(fn, f.Type))
		}
	}
	if len(c.Fields) == 0 {
		p.line("ignore w")
		p.line("ignore v")
	}
	p.out()
	p.line("")
	p.line("static member internal ReadFrom(r: BitPackerReader) : %s =", n)
	p.in()
	p.line("r.Enter()")
	var inits []string
	for i, f := range c.Fields {
		if f.IsArray {
			p.line("let n%d = r.Count()", i)
			p.line("let a%d : %s[] = Array.zeroCreate n%d", i, fsharpScalar(f.Type), i)
			p.line("for i in 0 .. n%d - 1 do a%d.[i] <- %s", i, i, fsharpRead(f.Type))
			p.line("let f%d = List.ofArray a%d", i, i)
		} else {
			p.line("let f%d = %s", i, fsharpRead(f.Type))
		}
		inits = append(inits, fmt.Sprintf("%s = f%d", fsharpField(f.Name), i))
	}
	p.line("r.Leave()")
	if len(c.Fields) == 0 {
		p.line("%s", n)
	} else {
		p.line("{ %s }", strings.Join(inits, "; "))
	}
	p.out()
	p.out()
}

const fsharpRuntime = `
/// Internal: signals malformed input; Decode turns it into an Error.
type internal BitPackerException(message: string) =
    inherit Exception(message)

type internal BitPackerWriter() =
    static let utf8 = UTF8Encoding(false, false)
    let mutable buf : byte[] = Array.zeroCreate 256
    let mutable pos = 0

    /// Fixed point: scaled is v * 10000 in the field's precision, truncated
    /// toward zero. NaN, infinities and out-of-range products raise
    /// ArgumentException (never saturated: a bare int64 conversion of an
    /// out-of-range value differs between .NET versions and CPUs).
    static member Fixed(scaled: float, kind: string, v: string) : int64 =
        if scaled >= -9223372036854775808.0 && scaled < 9223372036854775808.0 then int64 scaled
        else
            invalidArg "value" (sprintf "BitPacker: %s value %s is NaN, infinite or too large for fixed point (v * 10000 must fit in an int64)" kind v)

    member private _.Reserve(n: int) =
        if pos + n > buf.Length then
            let mutable cap = buf.Length * 2
            while cap < pos + n do
                cap <- cap * 2
            let next : byte[] = Array.zeroCreate cap
            Buffer.BlockCopy(buf, 0, next, 0, pos)
            buf <- next

    /// Unsigned LEB128.
    member private this.UVarint(u0: uint64) =
        this.Reserve 10
        let mutable u = u0
        while u >= 0x80UL do
            buf.[pos] <- byte ((u &&& 0x7FUL) ||| 0x80UL)
            pos <- pos + 1
            u <- u >>> 7
        buf.[pos] <- byte u
        pos <- pos + 1

    member this.Int(v: int32) = this.UVarint(uint64 (uint32 ((v <<< 1) ^^^ (v >>> 31))))

    member this.Long(v: int64) = this.UVarint(uint64 ((v <<< 1) ^^^ (v >>> 63)))

    /// v * 10000 in single precision (float32), exactly as the Go/Java targets.
    member this.Float(v: float32) =
        let scaled : float32 = v * 10000.0f
        this.Long(BitPackerWriter.Fixed(float scaled, "float", string v))

    member this.Double(v: float) = this.Long(BitPackerWriter.Fixed(v * 10000.0, "double", string v))

    member this.Bool(v: bool) =
        this.Reserve 1
        buf.[pos] <- (if v then 1uy else 0uy)
        pos <- pos + 1

    member this.String(v: string) =
        let b = utf8.GetBytes(v)
        this.Long(int64 b.Length)
        this.Reserve b.Length
        Buffer.BlockCopy(b, 0, buf, pos, b.Length)
        pos <- pos + b.Length

    member _.ToArray() : byte[] = Array.sub buf 0 pos

type internal BitPackerReader(buf: byte[]) =
    static let utf8 = UTF8Encoding(false, true)
    let mutable pos = 0
    let mutable depth = 0

    member _.Fail<'T>(msg: string) : 'T =
        raise (BitPackerException(sprintf "%s at byte %d" msg pos))

    member private this.Byte() : int =
        if pos >= buf.Length then this.Fail "truncated input"
        else
            let b = int buf.[pos]
            pos <- pos + 1
            b

    /// Unsigned LEB128, at most 10 bytes / 64 bits.
    member private this.UVarint() : uint64 =
        let mutable result = 0UL
        let mutable shift = 0
        let mutable b = 0x80
        while b >= 0x80 do
            b <- this.Byte()
            if shift = 63 && b > 1 then this.Fail "varint overflows 64 bits"
            result <- result ||| (uint64 (b &&& 0x7F) <<< shift)
            shift <- shift + 7
        result

    member this.Long() : int64 =
        let u = this.UVarint()
        int64 (u >>> 1) ^^^ -(int64 (u &&& 1UL))

    member this.Int() : int32 =
        let u = this.UVarint()
        if u > 0xFFFFFFFFUL then this.Fail "int out of 32-bit range"
        else
            let x = uint32 u
            int32 (x >>> 1) ^^^ -(int32 (x &&& 1u))

    member this.Float() : float32 = float32 (this.Long()) / 10000.0f

    member this.Double() : float = float (this.Long()) / 10000.0

    member this.Bool() : bool = this.Byte() <> 0

    /// Array element count: must be >= 0 and no larger than the bytes left.
    member this.Count() : int =
        let n = this.Int()
        if n < 0 || n > buf.Length - pos then this.Fail(sprintf "bad array length %d" n)
        else n

    member this.String() : string =
        let n = this.Long()
        if n < 0L || n > int64 (buf.Length - pos) then this.Fail(sprintf "bad string length %d" n)
        else
            let len = int n
            let s =
                try utf8.GetString(buf, pos, len)
                with :? ArgumentException -> this.Fail "invalid UTF-8"
            pos <- pos + len
            s

    member this.Version(expected: string) =
        let v = this.String()
        if v <> expected then
            raise (BitPackerException(sprintf "version mismatch: expected %s, got %s" expected v))

    member this.Enter() =
        depth <- depth + 1
        if depth > 512 then this.Fail "nesting deeper than 512"

    member _.Leave() = depth <- depth - 1
`
