package main

// OCaml target: `--lang ocaml` (alias `ml`).
//
// Writes <schema>.ml: one record type per class (int32 / int64 / float /
// bool / string / list), encode_<class> : <class> -> string,
// decode_<class> : string -> (<class>, string) result, decode_<class>_exn
// (raises Decode_error), default_<class> : unit -> <class>, and a
// submodule per class (e.g. World_state / WorldState) re-exporting them as
// t / encode / decode / decode_exn / default. See docs/ocaml.md.

import (
	"fmt"
	"strings"
	"unicode"
)

func init() { registerGenerator(genOCaml, "ocaml", "ml") }

var ocamlKeywords = map[string]bool{
	"and": true, "as": true, "assert": true, "asr": true, "begin": true, "class": true,
	"constraint": true, "do": true, "done": true, "downto": true, "else": true, "end": true,
	"exception": true, "external": true, "false": true, "for": true, "fun": true, "function": true,
	"functor": true, "if": true, "in": true, "include": true, "inherit": true, "initializer": true,
	"land": true, "lazy": true, "let": true, "lor": true, "lsl": true, "lsr": true, "lxor": true,
	"match": true, "method": true, "mod": true, "module": true, "mutable": true, "new": true,
	"nonrec": true, "object": true, "of": true, "open": true, "or": true, "private": true,
	"rec": true, "sig": true, "struct": true, "then": true, "to": true, "true": true, "try": true,
	"type": true, "val": true, "virtual": true, "when": true, "while": true, "with": true,
	// names the generated code itself uses
	"version": true, "result": true, "string": true, "int32": true, "int64": true, "float": true,
	"bool": true, "list": true, "unit": true, "t": true,
}

// ocamlLower makes a lower-case OCaml identifier (type, label).
func ocamlLower(s string) string {
	s = funclangSnake(s)
	r := []rune(s)
	if !unicode.IsLetter(r[0]) && r[0] != '_' {
		s = "x" + s
	}
	if ocamlKeywords[s] {
		s += "_"
	}
	return s
}

func ocamlTypeName(c string) string { return ocamlLower(c) }

func ocamlLabel(f string) string {
	r := []rune(f)
	if unicode.IsUpper(r[0]) {
		r[0] = unicode.ToLower(r[0])
	}
	s := string(r)
	if ocamlKeywords[s] {
		s += "_"
	}
	return s
}

// ocamlModName: "WorldState" -> "World_state" would be odd; keep the schema's
// class name, capitalised.
func ocamlModName(c string) string {
	r := []rune(c)
	r[0] = unicode.ToUpper(r[0])
	if !unicode.IsLetter(r[0]) {
		return "M" + c
	}
	return string(r)
}

func ocamlScalar(t string) string {
	switch t {
	case "int":
		return "int32"
	case "long":
		return "int64"
	case "float", "double":
		return "float"
	case "bool":
		return "bool"
	case "string":
		return "string"
	}
	return ocamlTypeName(t)
}

func ocamlDefault(f Field) string {
	if f.IsArray {
		return "[]"
	}
	switch f.Type {
	case "int":
		return "0l"
	case "long":
		return "0L"
	case "float", "double":
		return "0."
	case "bool":
		return "false"
	case "string":
		return `""`
	}
	return "default_" + ocamlTypeName(f.Type) + " ()"
}

func ocamlWriter(t string) string {
	if funclangIsScalar(t) {
		return "bp_put_" + t
	}
	return "w_" + ocamlTypeName(t)
}

func ocamlReader(t string) string {
	if funclangIsScalar(t) {
		return "bp_get_" + t
	}
	return "r_" + ocamlTypeName(t)
}

func genOCaml(classes []Class, cfg GeneratorConfig) error {
	if err := funclangCheck(classes); err != nil {
		return err
	}
	byName := funclangByName(classes)
	file := ocamlLower(cfg.InputFileName)

	var b strings.Builder
	fmt.Fprintf(&b, "(* Generated by BitPacker from %s.buff (schema version %s). Do not edit. *)\n\n", cfg.InputFileName, cfg.Version)
	fmt.Fprintf(&b, "let version = %q\n\n", cfg.Version)
	b.WriteString("(** Raised by the [decode_*_exn] functions; the [decode_*] functions\n    return it as [Error message] instead. *)\nexception Decode_error of string\n\n")

	// types, dependency-ordered; mutually recursive classes share a group
	for _, g := range funclangGroups(classes) {
		for i, c := range g {
			kw := "type"
			if i > 0 {
				kw = "and"
			}
			if len(c.Fields) == 0 {
				fmt.Fprintf(&b, "%s %s = unit\n", kw, ocamlTypeName(c.Name))
				continue
			}
			fmt.Fprintf(&b, "%s %s = {\n", kw, ocamlTypeName(c.Name))
			for _, f := range c.Fields {
				ty := ocamlScalar(f.Type)
				if f.IsArray {
					ty += " list"
				}
				fmt.Fprintf(&b, "  %s : %s;\n", ocamlLabel(f.Name), ty)
			}
			b.WriteString("}\n")
		}
		b.WriteString("\n")
	}

	b.WriteString(ocamlRuntime)

	// defaults
	b.WriteString("\n(* ---- defaults ---- *)\n\n")
	for i, c := range classes {
		kw := "let rec"
		if i > 0 {
			kw = "and"
		}
		t := ocamlTypeName(c.Name)
		if len(c.Fields) == 0 {
			fmt.Fprintf(&b, "%s default_%s () : %s = ()\n", kw, t, t)
			continue
		}
		fmt.Fprintf(&b, "%s default_%s () : %s = {\n", kw, t, t)
		for _, f := range c.Fields {
			fmt.Fprintf(&b, "  %s = %s;\n", ocamlLabel(f.Name), ocamlDefault(f))
		}
		b.WriteString("}\n")
	}

	// writers
	b.WriteString("\n(* ---- class bodies ---- *)\n\n")
	for i, c := range classes {
		kw := "let rec"
		if i > 0 {
			kw = "and"
		}
		t := ocamlTypeName(c.Name)
		if len(c.Fields) == 0 {
			fmt.Fprintf(&b, "%s w_%s (_ : Buffer.t) (() : %s) = ()\n", kw, t, t)
			continue
		}
		fmt.Fprintf(&b, "%s w_%s buf (v : %s) =\n", kw, t, t)
		for j, f := range c.Fields {
			sep := ";"
			if j == len(c.Fields)-1 {
				sep = ""
			}
			if f.IsArray {
				fmt.Fprintf(&b, "  bp_put_list %s buf v.%s%s\n", ocamlWriter(f.Type), ocamlLabel(f.Name), sep)
			} else {
				fmt.Fprintf(&b, "  %s buf v.%s%s\n", ocamlWriter(f.Type), ocamlLabel(f.Name), sep)
			}
		}
	}
	b.WriteString("\n")
	for i, c := range classes {
		kw := "let rec"
		if i > 0 {
			kw = "and"
		}
		t := ocamlTypeName(c.Name)
		if len(c.Fields) == 0 {
			fmt.Fprintf(&b, "%s r_%s (_ : string) (_ : int ref) : %s = ()\n", kw, t, t)
			continue
		}
		fmt.Fprintf(&b, "%s r_%s s pos : %s =\n", kw, t, t)
		for j, f := range c.Fields {
			if f.IsArray {
				min := "false"
				if funclangMinOneByte(f.Type, byName, map[string]bool{}) {
					min = "true"
				}
				fmt.Fprintf(&b, "  let f%d = bp_get_list %s %s s pos in\n", j+1, min, ocamlReader(f.Type))
			} else {
				fmt.Fprintf(&b, "  let f%d = %s s pos in\n", j+1, ocamlReader(f.Type))
			}
		}
		b.WriteString("  {")
		for j, f := range c.Fields {
			if j > 0 {
				b.WriteString(";")
			}
			fmt.Fprintf(&b, " %s = f%d", ocamlLabel(f.Name), j+1)
		}
		b.WriteString(" }\n")
	}

	// public API
	b.WriteString("\n(* ---- messages ---- *)\n")
	for _, c := range classes {
		t := ocamlTypeName(c.Name)
		fmt.Fprintf(&b, `
(** Encode as a version-prefixed message. Raises [Invalid_argument] for a
    NaN, infinite or out-of-range float/double. *)
let encode_%[1]s (v : %[1]s) : string =
  let buf = Buffer.create 64 in
  bp_put_string buf version;
  w_%[1]s buf v;
  Buffer.contents buf

(** Decode a version-prefixed message; bytes after it are ignored.
    Raises [Decode_error]. *)
let decode_%[1]s_exn (s : string) : %[1]s =
  let pos = ref 0 in
  let v = bp_get_string s pos in
  if v <> version then
    bp_fail (Printf.sprintf "version mismatch: expected %%S, got %%S" version v);
  r_%[1]s s pos

(** Decode a version-prefixed message; bytes after it are ignored. *)
let decode_%[1]s (s : string) : (%[1]s, string) result =
  match decode_%[1]s_exn s with
  | v -> Ok v
  | exception Decode_error msg -> Error msg
`, t)
	}

	// per-class modules
	b.WriteString("\n(* ---- one module per class ---- *)\n")
	for _, c := range classes {
		t := ocamlTypeName(c.Name)
		fmt.Fprintf(&b, "\nmodule %s = struct\n", ocamlModName(c.Name))
		if len(c.Fields) == 0 {
			fmt.Fprintf(&b, "  type t = %s\n", t)
		} else {
			fmt.Fprintf(&b, "  type t = %s = {\n", t)
			for _, f := range c.Fields {
				ty := ocamlScalar(f.Type)
				if f.IsArray {
					ty += " list"
				}
				fmt.Fprintf(&b, "    %s : %s;\n", ocamlLabel(f.Name), ty)
			}
			b.WriteString("  }\n")
		}
		fmt.Fprintf(&b, "  let encode = encode_%[1]s\n  let decode = decode_%[1]s\n  let decode_exn = decode_%[1]s_exn\n  let default = default_%[1]s\nend\n", t)
	}
	return funclangWrite(cfg.OutDir, file+".ml", b.String())
}

const ocamlRuntime = `(* ---- wire runtime (cross_lang_test/edge/README.md) ---- *)

let bp_fail msg = raise (Decode_error msg)

(* unsigned LEB128 of a 64-bit pattern *)
let bp_put_uvarint buf (v : int64) =
  let v = ref v in
  while Int64.logand !v (Int64.lognot 0x7FL) <> 0L do
    Buffer.add_char buf (Char.unsafe_chr (Int64.to_int (Int64.logand !v 0x7FL) lor 0x80));
    v := Int64.shift_right_logical !v 7
  done;
  Buffer.add_char buf (Char.unsafe_chr (Int64.to_int !v))

let bp_put_int buf (v : int32) =
  let z = Int32.logxor (Int32.shift_left v 1) (Int32.shift_right v 31) in
  bp_put_uvarint buf (Int64.logand (Int64.of_int32 z) 0xFFFFFFFFL)

let bp_put_long buf (v : int64) =
  bp_put_uvarint buf (Int64.logxor (Int64.shift_left v 1) (Int64.shift_right v 63))

(* Round a double to the nearest float32 (as a double). *)
let bp_f32 (x : float) = Int32.float_of_bits (Int32.bits_of_float x)

(* Fixed point: trunc(s) as a long; s = v * 10000. *)
let bp_put_fixed buf (s : float) =
  if Float.is_nan s || s < -9.223372036854775808e18 || s >= 9.223372036854775808e18 then
    invalid_arg (Printf.sprintf "BitPacker: float/double out of fixed-point range: %h" s);
  bp_put_long buf (Int64.of_float s)

(* float fields: OCaml floats are doubles, so the value is first rounded to
   float32 and the x10000 is rounded to float32 again, which is exactly the
   single-precision product the float32 targets compute. *)
let bp_put_float buf (v : float) = bp_put_fixed buf (bp_f32 (bp_f32 v *. 10000.))

let bp_put_double buf (v : float) = bp_put_fixed buf (v *. 10000.)

let bp_put_bool buf b = Buffer.add_char buf (if b then '\001' else '\000')

let bp_put_string buf (s : string) =
  bp_put_long buf (Int64.of_int (String.length s));
  Buffer.add_string buf s

let bp_put_list put buf l =
  bp_put_int buf (Int32.of_int (List.length l));
  List.iter (put buf) l

let bp_byte (s : string) pos =
  if !pos >= String.length s then bp_fail "truncated";
  let c = String.unsafe_get s !pos in
  incr pos;
  Char.code c

let bp_get_uvarint s pos =
  let rec go shift acc =
    let b = bp_byte s pos in
    let acc = Int64.logor acc (Int64.shift_left (Int64.of_int (b land 0x7F)) shift) in
    if b land 0x80 = 0 then acc
    else if shift >= 63 then bp_fail "varint too long"
    else go (shift + 7) acc
  in
  go 0 0L

let bp_get_int s pos =
  let z = Int64.to_int32 (bp_get_uvarint s pos) in
  Int32.logxor (Int32.shift_right_logical z 1) (Int32.neg (Int32.logand z 1l))

let bp_get_long s pos =
  let z = bp_get_uvarint s pos in
  Int64.logxor (Int64.shift_right_logical z 1) (Int64.neg (Int64.logand z 1L))

(* Correctly rounded int64 -> float32; going through a double would round
   twice above 2^53. *)
let bp_int64_to_f32 (n : int64) =
  if Int64.compare n (-0x20000000000000L) > 0 && Int64.compare n 0x20000000000000L < 0 then
    bp_f32 (Int64.to_float n)
  else
    let a = Int64.abs n (* min_int stays min_int: read unsigned below *) in
    let sticky = if Int64.logand a 0x7FFL <> 0L then 1L else 0L in
    let y = Int64.logor (Int64.shift_right_logical a 11) sticky in
    let f = bp_f32 (Int64.to_float y *. 2048.) in
    if Int64.compare n 0L < 0 then -.f else f

let bp_get_float s pos = bp_f32 (bp_int64_to_f32 (bp_get_long s pos) /. 10000.)

let bp_get_double s pos = Int64.to_float (bp_get_long s pos) /. 10000.

let bp_get_bool s pos = bp_byte s pos <> 0

let bp_get_string s pos =
  let n = bp_get_long s pos in
  if Int64.compare n 0L < 0 then bp_fail "negative string length";
  if Int64.compare n (Int64.of_int (String.length s - !pos)) > 0 then bp_fail "truncated";
  let n = Int64.to_int n in
  let v = String.sub s !pos n in
  pos := !pos + n;
  if not (String.is_valid_utf_8 v) then bp_fail "invalid UTF-8";
  v

(* min_one: every element takes at least one byte, so a count larger than
   the bytes left is rejected before any element is read. *)
let bp_get_list min_one get s pos =
  let n = Int32.to_int (bp_get_int s pos) in
  if n < 0 then bp_fail "negative array length";
  if min_one && n > String.length s - !pos then bp_fail "truncated";
  let rec go i acc = if i = 0 then List.rev acc else go (i - 1) (get s pos :: acc) in
  go n []

let _ = (bp_put_float, bp_put_double, bp_get_float, bp_get_double)
`
