package main

// D target: one module per schema, <input>.d, with a struct per schema class,
// `encode` (-> ubyte[], built with an Appender) and `T.decode` (throws
// BitPackerException). Everything is @safe; only Phobos is used. See docs/d.md.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func init() { registerGenerator(genD, "d") }

var dlangKeywords = map[string]bool{
	"abstract": true, "alias": true, "align": true, "asm": true, "assert": true, "auto": true,
	"body": true, "bool": true, "break": true, "byte": true, "case": true, "cast": true,
	"catch": true, "cdouble": true, "cent": true, "cfloat": true, "char": true, "class": true,
	"const": true, "continue": true, "creal": true, "dchar": true, "debug": true, "default": true,
	"delegate": true, "delete": true, "deprecated": true, "do": true, "double": true, "else": true,
	"enum": true, "export": true, "extern": true, "false": true, "final": true, "finally": true,
	"float": true, "for": true, "foreach": true, "foreach_reverse": true, "function": true,
	"goto": true, "idouble": true, "if": true, "ifloat": true, "immutable": true, "import": true,
	"in": true, "inout": true, "int": true, "interface": true, "invariant": true, "ireal": true,
	"is": true, "lazy": true, "long": true, "macro": true, "mixin": true, "module": true,
	"new": true, "nothrow": true, "null": true, "out": true, "override": true, "package": true,
	"pragma": true, "private": true, "protected": true, "public": true, "pure": true, "real": true,
	"ref": true, "return": true, "scope": true, "shared": true, "short": true, "static": true,
	"struct": true, "super": true, "switch": true, "synchronized": true, "template": true,
	"this": true, "throw": true, "true": true, "try": true, "typeid": true, "typeof": true,
	"ubyte": true, "ucent": true, "uint": true, "ulong": true, "union": true, "unittest": true,
	"ushort": true, "version": true, "void": true, "wchar": true, "while": true, "with": true,
	// Names the generated struct bodies refer to or define; a field with one
	// of these names would shadow them inside the struct.
	"string": true, "encode": true, "encodeTo": true, "decode": true, "decodeFrom": true,
	"schemaVersion": true, "BitPackerReader": true, "BitPackerException": true, "Appender": true,
	"BpWriter": true, "object": true, "size_t": true, "init": true, "sizeof": true,
	"alignof": true, "mangleof": true, "stringof": true, "tupleof": true,
}

var dlangReserved = map[string]bool{"BitPackerReader": true, "BitPackerException": true, "Appender": true, "BpWriter": true}

func dlangScalar(t string) (typ, method string, ok bool) {
	switch t {
	case "int":
		return "int", "Int", true
	case "long":
		return "long", "Long", true
	case "float":
		return "float", "Float", true
	case "double":
		return "double", "Double", true
	case "bool":
		return "bool", "Bool", true
	case "string":
		return "string", "String", true
	}
	return "", "", false
}

// dlangFieldName: snake_case -> camelCase (D style), keywords get a trailing '_'.
func dlangFieldName(n string) string {
	s := nimFieldName(n)
	if dlangKeywords[s] || strings.HasPrefix(s, "__") {
		s += "_"
	}
	return s
}

func dlangModuleName(stem string) string {
	s := nimModuleName(stem)
	if dlangKeywords[s] {
		s += "_"
	}
	return s
}

func genD(classes []Class, cfg GeneratorConfig) error {
	for _, c := range classes {
		if dlangReserved[crystalTypeName(c.Name)] {
			return fmt.Errorf("d: class name %q collides with a generated runtime name", c.Name)
		}
		seen := map[string]string{}
		for _, f := range c.Fields {
			n := dlangFieldName(f.Name)
			if prev, dup := seen[n]; dup {
				return fmt.Errorf("d: fields %s.%s and %s.%s both map to %q", c.Name, prev, c.Name, f.Name, n)
			}
			seen[n] = f.Name
		}
	}
	module := dlangModuleName(cfg.InputFileName)

	var b strings.Builder
	w := func(format string, a ...interface{}) { fmt.Fprintf(&b, format, a...) }

	w("// Generated by BitPacker from %s.buff (schema version %s). Do not edit.\n", cfg.InputFileName, cfg.Version)
	w("//\n// Wire format: tools/bit-packer/cross_lang_test/edge/README.md\n// API: tools/bit-packer/docs/d.md\n")
	w("module %s;\n\n", module)
	w("import std.array : Appender;\n\n")
	w("/// Schema version written first in every message and checked by `decode`.\n")
	w("enum string schemaVersion = %q;\n", cfg.Version)
	b.WriteString(dlangRuntime)

	for _, c := range classes {
		n := crystalTypeName(c.Name)
		w("\n/// Schema class `%s`.\nstruct %s\n{\n", c.Name, n)
		for _, f := range c.Fields {
			typ, _, ok := dlangScalar(f.Type)
			if !ok {
				typ = crystalTypeName(f.Type)
			}
			if f.IsArray {
				typ += "[]"
			}
			w("    %s %s;\n", typ, dlangFieldName(f.Name))
		}
		w("\n    /// Encodes this value as a complete, version-prefixed message.\n")
		w("    ubyte[] encode() const @safe\n    {\n        BpWriter w;\n        w.bpPutString(schemaVersion);\n        encodeTo(w);\n        return w.data;\n    }\n")
		w("\n    /// Appends this value's fields (no version prefix) to `w`.\n")
		w("    void encodeTo(ref Appender!(ubyte[]) w) const @safe\n    {\n")
		for _, f := range c.Fields {
			fn := dlangFieldName(f.Name)
			_, m, scalar := dlangScalar(f.Type)
			put := func(x string) string {
				if scalar {
					return "w.bpPut" + m + "(" + x + ")"
				}
				return x + ".encodeTo(w)"
			}
			if f.IsArray {
				w("        w.bpPutCount(this.%s.length);\n", fn)
				w("        foreach (ref e; this.%s) %s;\n", fn, put("e"))
			} else {
				w("        %s;\n", put("this."+fn))
			}
		}
		w("    }\n")
		w("\n    /// Decodes a message produced by `encode`. Throws `BitPackerException` on a\n")
		w("    /// wrong version prefix or truncated/malformed input. Trailing bytes are ignored.\n")
		w("    static %s decode(const(ubyte)[] data) @safe\n    {\n", n)
		w("        auto r = BitPackerReader(data);\n        r.checkVersion();\n        return decodeFrom(r);\n    }\n")
		w("\n    /// Reads this struct's fields (no version prefix) from `r`.\n")
		w("    static %s decodeFrom(ref BitPackerReader r) @safe\n    {\n        %s o;\n", n, n)
		for _, f := range c.Fields {
			fn := dlangFieldName(f.Name)
			typ, m, scalar := dlangScalar(f.Type)
			get := "r.get" + m + "()"
			if !scalar {
				typ = crystalTypeName(f.Type)
				get = typ + ".decodeFrom(r)"
			}
			if f.IsArray {
				w("        o.%s = new %s[](r.getCount());\n", fn, typ)
				w("        foreach (ref e; o.%s) e = %s;\n", fn, get)
			} else {
				w("        o.%s = %s;\n", fn, get)
			}
		}
		w("        return o;\n    }\n}\n")
	}

	if err := os.MkdirAll(cfg.OutDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(cfg.OutDir, module+".d"), []byte(b.String()), 0644)
}

const dlangRuntime = `
/// Thrown by ` + "`decode`" + ` for a wrong version prefix, truncated or malformed input.
class BitPackerException : Exception
{
    this(string msg, string file = __FILE__, size_t line = __LINE__) @safe pure nothrow
    {
        super(msg, file, line);
    }
}

private alias BpWriter = Appender!(ubyte[]);

private void bpUvarint(ref BpWriter w, ulong v) @safe pure nothrow
{
    while (v >= 0x80)
    {
        w.put(cast(ubyte)((v & 0x7F) | 0x80));
        v >>= 7;
    }
    w.put(cast(ubyte) v);
}

// D integer arithmetic wraps, so the zigzag shifts are well defined.
private void bpPutInt(ref BpWriter w, int v) @safe pure nothrow
{
    w.bpUvarint(cast(uint)((v << 1) ^ (v >> 31)));
}

private void bpPutLong(ref BpWriter w, long v) @safe pure nothrow
{
    w.bpUvarint(cast(ulong)((v << 1) ^ (v >> 63)));
}

// Truncates toward zero; NaN -> 0, out of range saturates (as Java does).
private long bpFixed(double p) @safe pure nothrow @nogc
{
    if (p != p) return 0;
    if (p >= 0x1p63) return long.max;
    if (p <= -0x1p63) return long.min;
    return cast(long) p;
}

// The x10000 product must be the float32 product, as in the Go and Java
// targets. D lets the compiler evaluate float expressions at higher precision,
// so compute the product in double (a float x float product is exact there)
// and round it once to float: that is exactly IEEE single multiplication.
private void bpPutFloat(ref BpWriter w, float v) @safe pure nothrow
{
    w.bpPutLong(bpFixed(cast(float)(cast(double) v * 10000.0)));
}

private void bpPutDouble(ref BpWriter w, double v) @safe pure nothrow
{
    w.bpPutLong(bpFixed(v * 10000.0));
}

private void bpPutBool(ref BpWriter w, bool v) @safe pure nothrow
{
    w.put(cast(ubyte)(v ? 1 : 0));
}

private void bpPutString(ref BpWriter w, string v) @safe pure nothrow
{
    import std.string : representation;
    w.bpPutLong(cast(long) v.length);
    w.put(v.representation);
}

private void bpPutCount(ref BpWriter w, size_t n) @safe pure nothrow
{
    assert(n <= int.max, "BitPacker: array longer than int.max");
    w.bpPutInt(cast(int) n);
}

/// Bounds-checked cursor over an input buffer, used by the generated
/// ` + "`decodeFrom`" + ` functions.
struct BitPackerReader
{
    private const(ubyte)[] data;
    private size_t pos;

    this(const(ubyte)[] data) @safe pure nothrow @nogc
    {
        this.data = data;
    }

    /// Bytes not yet consumed.
    size_t remaining() const @safe pure nothrow @nogc
    {
        return data.length - pos;
    }

    private noreturn fail(string msg) @safe pure
    {
        import std.conv : to;
        throw new BitPackerException(msg ~ " at byte " ~ pos.to!string);
    }

    ubyte getByte() @safe pure
    {
        if (pos >= data.length) fail("unexpected end of input");
        return data[pos++];
    }

    private ulong getUvarint() @safe pure
    {
        ulong result;
        for (uint shift = 0;; shift += 7)
        {
            immutable b = getByte();
            if (shift == 63 && b > 1) fail("varint overflows 64 bits");
            result |= cast(ulong)(b & 0x7F) << shift;
            if (b < 0x80) return result;
        }
    }

    int getInt() @safe pure
    {
        immutable u = getUvarint();
        if (u > uint.max) fail("int varint overflows 32 bits");
        immutable v = cast(uint) u;
        return cast(int)((v >> 1) ^ (0u - (v & 1)));
    }

    long getLong() @safe pure
    {
        immutable u = getUvarint();
        return cast(long)((u >> 1) ^ (0UL - (u & 1)));
    }

    /// float32(n) / 10000 in single precision, as Go/Java decode. The double
    /// quotient rounded once to float equals the IEEE float quotient.
    float getFloat() @safe pure
    {
        immutable float n = cast(float) getLong();
        return cast(float)(cast(double) n / 10000.0);
    }

    double getDouble() @safe pure
    {
        return cast(double) getLong() / 10000.0;
    }

    bool getBool() @safe pure
    {
        return getByte() != 0;
    }

    string getString() @safe
    {
        import std.utf : validate, UTFException;
        immutable n = getLong();
        if (n < 0 || cast(ulong) n > remaining) fail("bad string length");
        immutable len = cast(size_t) n;
        string s = cast(string) data[pos .. pos + len].idup;
        pos += len;
        try
            validate(s);
        catch (UTFException)
            fail("string is not valid UTF-8");
        return s;
    }

    /// Array element count. Every element takes at least one byte, so a count
    /// larger than the remaining input is rejected before anything is allocated.
    size_t getCount() @safe pure
    {
        immutable n = getInt();
        if (n < 0 || cast(size_t) n > remaining) fail("bad array length");
        return cast(size_t) n;
    }

    /// Reads the version prefix and throws unless it is ` + "`schemaVersion`" + `.
    void checkVersion() @safe
    {
        immutable v = getString();
        if (v != schemaVersion)
            throw new BitPackerException("version mismatch: expected " ~ schemaVersion ~ ", got " ~ v);
    }
}
`
