package main

// Dart target: `--lang dart`. Writes <schema>.dart: one immutable class
// (final fields, const constructor with named, defaulted parameters, value
// ==/hashCode) per schema class, with encode(): Uint8List and static
// decode(Uint8List) that throws BitPackerException. dart:core,
// dart:convert and dart:typed_data only. `long` is a Dart int, which is
// 64-bit on the Dart VM and AOT but a double under dart2js/JS: the
// generated code is for the VM/AOT/Flutter native only. See docs/dart.md.

import (
	"fmt"
	"strings"
)

func init() { registerGenerator(genDart, "dart") }

var dartReserved = map[string]bool{
	// Reserved words and built-in identifiers.
	"abstract": true, "as": true, "assert": true, "async": true, "await": true, "base": true,
	"break": true, "case": true, "catch": true, "class": true, "const": true, "continue": true,
	"covariant": true, "default": true, "deferred": true, "do": true, "dynamic": true, "else": true,
	"enum": true, "export": true, "extends": true, "extension": true, "external": true,
	"factory": true, "false": true, "final": true, "finally": true, "for": true, "Function": true,
	"get": true, "hide": true, "if": true, "implements": true, "import": true, "in": true,
	"interface": true, "is": true, "late": true, "library": true, "mixin": true, "new": true,
	"null": true, "of": true, "on": true, "operator": true, "part": true, "required": true,
	"rethrow": true, "return": true, "sealed": true, "set": true, "show": true, "static": true,
	"super": true, "switch": true, "sync": true, "this": true, "throw": true, "true": true,
	"try": true, "type": true, "typedef": true, "var": true, "void": true, "when": true,
	"while": true, "with": true, "yield": true,
	// Members every class has or the generated class defines, and type names
	// the generated class body refers to.
	"encode": true, "hashCode": true, "runtimeType": true, "toString": true, "noSuchMethod": true,
	"int": true, "double": true, "bool": true, "String": true, "List": true, "Object": true,
	"identical": true, "other": true,
}

func dartField(name string) string {
	n := polyglotCamel(name)
	if strings.HasPrefix(n, "_") {
		// A leading underscore would make the field library-private.
		n = "f" + n
	}
	if dartReserved[n] {
		n += "_"
	}
	return n
}

func dartScalar(t string) string {
	switch t {
	case "int", "long":
		return "int"
	case "float", "double":
		return "double"
	case "bool":
		return "bool"
	case "string":
		return "String"
	}
	return t
}

func dartType(f Field) string {
	if f.IsArray {
		return "List<" + dartScalar(f.Type) + ">"
	}
	return dartScalar(f.Type)
}

func dartDefault(f Field) string {
	if f.IsArray {
		return "const <" + dartScalar(f.Type) + ">[]"
	}
	switch f.Type {
	case "int", "long":
		return "0"
	case "float", "double":
		return "0.0"
	case "bool":
		return "false"
	case "string":
		return "''"
	}
	return "const " + f.Type + "()"
}

func dartRead(t string) string {
	if polyglotIsScalar(t) {
		return "r.read" + polyglotPascal(t) + "()"
	}
	return "_bpRead" + t + "(r)"
}

func dartWrite(expr, t string) string {
	if polyglotIsScalar(t) {
		return "w.write" + polyglotPascal(t) + "(" + expr + ");"
	}
	return "_bpWrite" + t + "(w, " + expr + ");"
}

func genDart(classes []Class, cfg GeneratorConfig) error {
	if err := polyglotValidate("dart", classes, dartField); err != nil {
		return err
	}
	if err := polyglotCheckClassNames("dart", classes, "BitPackerException", "String", "int", "double",
		"bool", "num", "List", "Uint8List", "Float32List", "Object", "Never", "Exception", "Function",
		"Map", "Iterable", "Null", "Type", "Symbol", "Record", "Future", "Stream"); err != nil {
		return err
	}
	for _, c := range classes {
		if strings.HasPrefix(c.Name, "_") {
			return fmt.Errorf("dart: class name %s starts with '_', which would make it library-private", c.Name)
		}
	}
	p := &polyglotLines{unit: "  "}
	p.line("// Generated by BitPacker from %s.buff (schema version %s). Do not edit.", cfg.InputFileName, cfg.Version)
	p.line("//")
	p.line("// Needs the Dart VM or AOT (including Flutter native): `long` fields are")
	p.line("// Dart ints, which are 64-bit there but doubles when compiled to JavaScript.")
	p.line("import 'dart:convert';")
	p.line("import 'dart:typed_data';")
	p.line("")
	p.line("/// The schema version every encoded message starts with.")
	p.line("const String bitPackerVersion = %s;", strings.ReplaceAll(polyglotQuote(cfg.Version), `$`, `\$`))
	p.raw(dartRuntime)
	for _, c := range classes {
		dartClass(p, c)
	}
	return polyglotWrite(cfg, cfg.InputFileName+".dart", p.String())
}

func dartClass(p *polyglotLines, c Class) {
	n := c.Name
	p.line("")
	p.line("class %s {", n)
	p.in()
	for _, f := range c.Fields {
		p.line("final %s %s;", dartType(f), dartField(f.Name))
	}
	if len(c.Fields) > 0 {
		p.line("")
		p.line("/// Omitted fields get zero values: 0, 0.0, false, '', const [] or a default instance.")
		p.line("const %s({", n)
		p.in()
		for _, f := range c.Fields {
			p.line("this.%s = %s,", dartField(f.Name), dartDefault(f))
		}
		p.out()
		p.line("});")
	} else {
		p.line("const %s();", n)
	}
	p.line("")
	p.line("/// Encodes this value as a version-prefixed BitPacker message. Throws an")
	p.line("/// [ArgumentError] if a float/double field is NaN, infinite or out of")
	p.line("/// fixed-point range.")
	p.line("Uint8List encode() {")
	p.line("  final w = _BpWriter();")
	p.line("  w.writeString(bitPackerVersion);")
	p.line("  _bpWrite%s(w, this);", n)
	p.line("  return w.toBytes();")
	p.line("}")
	p.line("")
	p.line("/// Decodes a version-prefixed message. Throws [BitPackerException] on a")
	p.line("/// version mismatch or malformed/truncated input.")
	p.line("static %s decode(Uint8List data) {", n)
	p.line("  final r = _BpReader(data);")
	p.line("  r.version(bitPackerVersion);")
	p.line("  return _bpRead%s(r);", n)
	p.line("}")
	p.line("")
	// ==
	var eqs, hashes, shows []string
	for _, f := range c.Fields {
		fn := dartField(f.Name)
		if f.IsArray {
			eqs = append(eqs, fmt.Sprintf("_bpListEq(%s, other.%s)", fn, fn))
			hashes = append(hashes, fmt.Sprintf("Object.hashAll(%s)", fn))
		} else {
			eqs = append(eqs, fmt.Sprintf("%s == other.%s", fn, fn))
			hashes = append(hashes, fn)
		}
		shows = append(shows, fmt.Sprintf("%s: $%s", fn, fn))
	}
	p.line("@override")
	if len(eqs) == 0 {
		p.line("bool operator ==(Object other) => other is %s;", n)
	} else {
		p.line("bool operator ==(Object other) =>")
		p.line("    identical(this, other) ||")
		p.line("    other is %s &&", n)
		for i, e := range eqs {
			end := " &&"
			if i == len(eqs)-1 {
				end = ";"
			}
			p.line("        %s%s", e, end)
		}
	}
	p.line("")
	p.line("@override")
	if len(hashes) == 0 {
		p.line("int get hashCode => %d;", len(n))
	} else {
		p.line("int get hashCode => Object.hashAll([%s]);", strings.Join(hashes, ", "))
	}
	p.line("")
	p.line("@override")
	p.line("String toString() => '%s(%s)';", n, strings.Join(shows, ", "))
	p.out()
	p.line("}")
	p.line("")
	p.line("void _bpWrite%s(_BpWriter w, %s v) {", n, n)
	p.in()
	for _, f := range c.Fields {
		fn := "v." + dartField(f.Name)
		if f.IsArray {
			p.line("w.writeInt(%s.length);", fn)
			p.line("for (final x in %s) {", fn)
			p.line("  %s", dartWrite("x", f.Type))
			p.line("}")
		} else {
			p.line("%s", dartWrite(fn, f.Type))
		}
	}
	p.out()
	p.line("}")
	p.line("")
	p.line("%s _bpRead%s(_BpReader r) {", n, n)
	p.in()
	p.line("r.enter();")
	var args []string
	for i, f := range c.Fields {
		if f.IsArray {
			p.line("final f%d = List<%s>.generate(r.count(), (_) => %s, growable: false);", i, dartScalar(f.Type), dartRead(f.Type))
		} else {
			p.line("final f%d = %s;", i, dartRead(f.Type))
		}
		args = append(args, fmt.Sprintf("%s: f%d", dartField(f.Name), i))
	}
	p.line("r.leave();")
	p.line("return %s(%s);", n, strings.Join(args, ", "))
	p.out()
	p.line("}")
}

const dartRuntime = `
/// Thrown by decode() on a version mismatch or malformed/truncated input.
class BitPackerException implements Exception {
  final String message;
  const BitPackerException(this.message);

  @override
  String toString() => 'BitPackerException: $message';
}

bool _bpListEq<T>(List<T> a, List<T> b) {
  if (identical(a, b)) return true;
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}

final Float32List _bpF32 = Float32List(1);

/// Rounds x to the nearest float32 (Dart has no float32 arithmetic).
double _bpToF32(double x) {
  _bpF32[0] = x;
  return _bpF32[0];
}

/// Fixed point: [scaled] is v * 10000 in the field's precision, truncated
/// toward zero. NaN, infinities and out-of-range products throw an
/// [ArgumentError] (never saturated or wrapped).
int _bpFixed(double scaled, String kind, double v) {
  if (scaled >= -9223372036854775808.0 && scaled < 9223372036854775808.0) {
    return scaled.truncate();
  }
  throw ArgumentError.value(
      v, kind, 'NaN, infinite or too large for BitPacker fixed point (v * 10000 must fit in 64 bits)');
}

class _BpWriter {
  Uint8List _buf = Uint8List(256);
  int _pos = 0;

  void _reserve(int n) {
    if (_pos + n <= _buf.length) return;
    var cap = _buf.length * 2;
    while (cap < _pos + n) {
      cap *= 2;
    }
    _buf = Uint8List(cap)..setRange(0, _pos, _buf);
  }

  /// Unsigned LEB128 of the 64 bits of u.
  void _uvarint(int u) {
    _reserve(10);
    while ((u & ~0x7F) != 0) {
      _buf[_pos++] = (u & 0x7F) | 0x80;
      u = u >>> 7;
    }
    _buf[_pos++] = u;
  }

  /// int: wrapped to 32 bits, zigzag, varint.
  void writeInt(int v) {
    final n = v.toSigned(32);
    _uvarint(((n << 1) ^ (n >> 31)) & 0xFFFFFFFF);
  }

  void writeLong(int v) => _uvarint((v << 1) ^ (v >> 63));

  /// v * 10000 in single precision (float32), exactly as the Go/Java targets.
  /// The product of two float32 values is exact in a double, so rounding it
  /// once to float32 is the IEEE float32 multiplication.
  void writeFloat(double v) => writeLong(_bpFixed(_bpToF32(_bpToF32(v) * 10000.0), 'float', v));

  void writeDouble(double v) => writeLong(_bpFixed(v * 10000.0, 'double', v));

  void writeBool(bool v) {
    _reserve(1);
    _buf[_pos++] = v ? 1 : 0;
  }

  /// Lone surrogates are encoded as U+FFFD (dart:convert behaviour).
  void writeString(String v) {
    final b = utf8.encode(v);
    writeLong(b.length);
    _reserve(b.length);
    _buf.setRange(_pos, _pos + b.length, b);
    _pos += b.length;
  }

  Uint8List toBytes() => _buf.sublist(0, _pos);
}

class _BpReader {
  final Uint8List _buf;
  int _pos = 0;
  int _depth = 0;

  _BpReader(this._buf);

  Never _fail(String msg) => throw BitPackerException('$msg at byte $_pos');

  int _byte() {
    if (_pos >= _buf.length) _fail('truncated input');
    return _buf[_pos++];
  }

  /// Unsigned LEB128, at most 10 bytes / 64 bits (returned as the int64 bit pattern).
  int _uvarint() {
    var result = 0;
    var shift = 0;
    var b = 0x80;
    while (b >= 0x80) {
      b = _byte();
      if (shift == 63 && b > 1) _fail('varint overflows 64 bits');
      result |= (b & 0x7F) << shift;
      shift += 7;
    }
    return result;
  }

  int readLong() {
    final u = _uvarint();
    return (u >>> 1) ^ -(u & 1);
  }

  int readInt() {
    final u = _uvarint();
    if (u < 0 || u > 0xFFFFFFFF) _fail('int out of 32-bit range');
    return (u >>> 1) ^ -(u & 1);
  }

  double readFloat() => _bpToF32(_bpToF32(readLong().toDouble()) / 10000.0);

  double readDouble() => readLong().toDouble() / 10000.0;

  bool readBool() => _byte() != 0;

  /// Array element count: must be >= 0 and no larger than the bytes left.
  int count() {
    final n = readInt();
    if (n < 0 || n > _buf.length - _pos) _fail('bad array length $n');
    return n;
  }

  String readString() {
    final n = readLong();
    if (n < 0 || n > _buf.length - _pos) _fail('bad string length $n');
    // utf8.decode drops a leading byte order mark; keep every U+FEFF.
    var start = _pos;
    final end = _pos + n;
    var boms = 0;
    while (end - start >= 3 && _buf[start] == 0xEF && _buf[start + 1] == 0xBB && _buf[start + 2] == 0xBF) {
      boms++;
      start += 3;
    }
    final String s;
    try {
      s = utf8.decode(Uint8List.sublistView(_buf, start, end));
    } on FormatException {
      _fail('invalid UTF-8');
    }
    _pos = end;
    return boms == 0 ? s : '\uFEFF' * boms + s;
  }

  void version(String expected) {
    final v = readString();
    if (v != expected) {
      throw BitPackerException('version mismatch: expected $expected, got $v');
    }
  }

  void enter() {
    if (++_depth > 512) _fail('nesting deeper than 512');
  }

  void leave() => _depth--;
}
`
