package main

// Scala target: `--lang scala`. Writes <schema>.scala in package --package
// (default "generated"): one final case class per schema class (arrays are
// Vector[T]), with encode(): Array[Byte] and a companion
// decode(Array[Byte]): Either[String, T]. Standard library + java.nio only;
// compiles as Scala 2.13 and Scala 3. See docs/scala.md.

import (
	"fmt"
	"strings"
)

func init() { registerGenerator(genScala, "scala") }

var scalaKeywords = map[string]bool{
	"abstract": true, "case": true, "catch": true, "class": true, "def": true, "do": true,
	"else": true, "extends": true, "false": true, "final": true, "finally": true, "for": true,
	"forSome": true, "if": true, "implicit": true, "import": true, "lazy": true, "match": true,
	"new": true, "null": true, "object": true, "override": true, "package": true, "private": true,
	"protected": true, "return": true, "sealed": true, "super": true, "this": true, "throw": true,
	"trait": true, "true": true, "try": true, "type": true, "val": true, "var": true,
	"while": true, "with": true, "yield": true, "macro": true,
	// Scala 3 hard keywords.
	"enum": true, "export": true, "given": true, "then": true,
}

// Names a case-class parameter cannot take because the case class (or the
// generated code) already defines a member of that name.
var scalaMembers = map[string]bool{
	"copy": true, "equals": true, "hashCode": true, "toString": true, "canEqual": true,
	"productArity": true, "productElement": true, "productIterator": true, "productPrefix": true,
	"productElementName": true, "productElementNames": true, "encode": true, "writeTo": true,
	"getClass": true, "wait": true, "notify": true, "notifyAll": true, "clone": true, "finalize": true,
}

func scalaField(name string) string {
	n := polyglotCamel(name)
	if scalaMembers[n] {
		n += "_"
	}
	if scalaKeywords[n] {
		return "`" + n + "`"
	}
	return n
}

func scalaScalar(t string) string {
	switch t {
	case "int":
		return "Int"
	case "long":
		return "Long"
	case "float":
		return "Float"
	case "double":
		return "Double"
	case "bool":
		return "Boolean"
	case "string":
		return "String"
	}
	return t
}

func scalaType(f Field) string {
	if f.IsArray {
		return "Vector[" + scalaScalar(f.Type) + "]"
	}
	return scalaScalar(f.Type)
}

func scalaDefault(f Field) string {
	if f.IsArray {
		return "Vector.empty"
	}
	switch f.Type {
	case "int":
		return "0"
	case "long":
		return "0L"
	case "float":
		return "0.0f"
	case "double":
		return "0.0"
	case "bool":
		return "false"
	case "string":
		return `""`
	}
	return f.Type + "()"
}

func scalaRead(t string) string {
	if polyglotIsScalar(t) {
		return "r." + t + "()"
	}
	return t + ".readFrom(r)"
}

func scalaWrite(expr, t string) string {
	if polyglotIsScalar(t) {
		return "w." + t + "(" + expr + ")"
	}
	return expr + ".writeTo(w)"
}

func genScala(classes []Class, cfg GeneratorConfig) error {
	if err := polyglotValidate("scala", classes, scalaField); err != nil {
		return err
	}
	if err := polyglotCheckClassNames("scala", classes, "BitPacker", "BitPackerWriter", "BitPackerReader",
		"BitPackerException", "String", "Int", "Long", "Float", "Double", "Boolean", "Vector", "Array",
		"Byte", "Either", "Left", "Right", "Exception", "Unit", "Any", "Nothing", "Char"); err != nil {
		return err
	}
	pkg := cfg.PackageName
	scope := pkg[strings.LastIndex(pkg, ".")+1:]
	p := &polyglotLines{unit: "  "}
	p.line("// Generated by BitPacker from %s.buff (schema version %s). Do not edit.", cfg.InputFileName, cfg.Version)
	p.line("package %s", pkg)
	p.line("")
	p.line("import java.nio.ByteBuffer")
	p.line("import java.nio.charset.{CharacterCodingException, CodingErrorAction, StandardCharsets}")
	p.line("")
	p.line("object BitPacker {")
	p.line("  /** The schema version every encoded message starts with. */")
	p.line("  final val Version = %s", polyglotQuote(cfg.Version))
	p.line("}")
	p.raw(strings.ReplaceAll(scalaRuntime, "SCOPE", scope))
	for _, c := range classes {
		scalaClass(p, c, scope)
	}
	return polyglotWrite(cfg, cfg.InputFileName+".scala", p.String())
}

func scalaClass(p *polyglotLines, c Class, scope string) {
	n := c.Name
	p.line("")
	if len(c.Fields) == 0 {
		p.line("final case class %s() {", n)
	} else {
		p.line("final case class %s(", n)
		p.in()
		for i, f := range c.Fields {
			sep := ","
			if i == len(c.Fields)-1 {
				sep = ""
			}
			fn := scalaField(f.Name)
			if strings.HasSuffix(fn, "_") {
				fn += " " // "x_:" would lex as one identifier
			}
			p.line("%s: %s = %s%s", fn, scalaType(f), scalaDefault(f), sep)
		}
		p.out()
		p.line(") {")
	}
	p.in()
	p.line("/** Encodes this value as a version-prefixed BitPacker message.")
	p.line("  * @throws IllegalArgumentException if a float/double field is NaN, infinite or out of fixed-point range")
	p.line("  */")
	p.line("def encode(): Array[Byte] = {")
	p.line("  val w = new BitPackerWriter")
	p.line("  w.string(BitPacker.Version)")
	p.line("  writeTo(w)")
	p.line("  w.toByteArray")
	p.line("}")
	p.line("")
	p.line("private[%s] def writeTo(w: BitPackerWriter): Unit = {", scope)
	p.in()
	for _, f := range c.Fields {
		fn := "this." + scalaField(f.Name)
		if f.IsArray {
			p.line("w.int(%s.length)", fn)
			p.line("%s.foreach(x => %s)", fn, scalaWrite("x", f.Type))
		} else {
			p.line("%s", scalaWrite(fn, f.Type))
		}
	}
	if len(c.Fields) == 0 {
		p.line("val _ = w")
	}
	p.out()
	p.line("}")
	p.out()
	p.line("}")
	p.line("")
	p.line("object %s {", n)
	p.in()
	p.line("/** Decodes a version-prefixed message: Left(reason) on a version mismatch or malformed/truncated input. */")
	p.line("def decode(data: Array[Byte]): Either[String, %s] =", n)
	p.line("  try {")
	p.line("    val r = new BitPackerReader(data)")
	p.line("    r.version(BitPacker.Version)")
	p.line("    Right(readFrom(r))")
	p.line("  } catch {")
	p.line("    case e: BitPackerException => Left(e.getMessage)")
	p.line("  }")
	p.line("")
	p.line("private[%s] def readFrom(r: BitPackerReader): %s = {", scope, n)
	p.in()
	p.line("r.enter()")
	var args []string
	for i, f := range c.Fields {
		if f.IsArray {
			p.line("val n%d = r.count()", i)
			p.line("val b%d = Vector.newBuilder[%s]", i, scalaScalar(f.Type))
			p.line("b%d.sizeHint(n%d)", i, i)
			p.line("var i%d = 0", i)
			p.line("while (i%d < n%d) { b%d += %s; i%d += 1 }", i, i, i, scalaRead(f.Type), i)
			p.line("val f%d = b%d.result()", i, i)
		} else {
			p.line("val f%d = %s", i, scalaRead(f.Type))
		}
		args = append(args, fmt.Sprintf("%s = f%d", scalaField(f.Name), i))
	}
	p.line("r.leave()")
	p.line("%s(%s)", n, strings.Join(args, ", "))
	p.out()
	p.line("}")
	p.out()
	p.line("}")
}

const scalaRuntime = `
/** Internal: signals malformed input; decode() turns it into a Left. */
private[SCOPE] final class BitPackerException(message: String) extends Exception(message)

private[SCOPE] final class BitPackerWriter {
  private var buf = new Array[Byte](256)
  private var pos = 0

  private def reserve(n: Int): Unit =
    if (pos + n > buf.length) {
      var cap = buf.length * 2
      while (cap < pos + n) cap *= 2
      buf = java.util.Arrays.copyOf(buf, cap)
    }

  /** Unsigned LEB128 of the 64 bits of u0. */
  private def uvarint(u0: Long): Unit = {
    reserve(10)
    var u = u0
    while ((u & ~0x7FL) != 0L) {
      buf(pos) = ((u & 0x7FL) | 0x80L).toByte
      pos += 1
      u = u >>> 7
    }
    buf(pos) = u.toByte
    pos += 1
  }

  def int(v: Int): Unit = uvarint(((v << 1) ^ (v >> 31)).toLong & 0xFFFFFFFFL)

  def long(v: Long): Unit = uvarint((v << 1) ^ (v >> 63))

  /** Fixed point: scaled is v * 10000 in the field's precision, truncated
    * toward zero. NaN, infinities and out-of-range products are rejected.
    */
  private def fixed(scaled: Double, kind: String, v: Any): Unit = {
    require(
      scaled >= -9.223372036854775808e18 && scaled < 9.223372036854775808e18,
      s"BitPacker: $kind value $v is NaN, infinite or too large for fixed point (v * 10000 must fit in a Long)"
    )
    long(scaled.toLong)
  }

  /** v * 10000 in single precision (float32), exactly as the Go/Java targets. */
  def float(v: Float): Unit = fixed((v * 10000.0f).toDouble, "float", v)

  def double(v: Double): Unit = fixed(v * 10000.0, "double", v)

  def bool(v: Boolean): Unit = {
    reserve(1)
    buf(pos) = if (v) 1.toByte else 0.toByte
    pos += 1
  }

  def string(v: String): Unit = {
    val b = v.getBytes(StandardCharsets.UTF_8)
    long(b.length.toLong)
    reserve(b.length)
    System.arraycopy(b, 0, buf, pos, b.length)
    pos += b.length
  }

  def toByteArray: Array[Byte] = java.util.Arrays.copyOf(buf, pos)
}

private[SCOPE] final class BitPackerReader(buf: Array[Byte]) {
  private var pos = 0
  private var depth = 0
  private val utf8 = StandardCharsets.UTF_8
    .newDecoder()
    .onMalformedInput(CodingErrorAction.REPORT)
    .onUnmappableCharacter(CodingErrorAction.REPORT)

  private def fail(msg: String): Nothing = throw new BitPackerException(msg + " at byte " + pos)

  private def byte(): Int = {
    if (pos >= buf.length) fail("truncated input")
    val b = buf(pos) & 0xFF
    pos += 1
    b
  }

  /** Unsigned LEB128, at most 10 bytes / 64 bits. */
  private def uvarint(): Long = {
    var result = 0L
    var shift = 0
    var b = 0x80
    while (b >= 0x80) {
      b = byte()
      if (shift == 63 && b > 1) fail("varint overflows 64 bits")
      result |= (b & 0x7F).toLong << shift
      shift += 7
    }
    result
  }

  def long(): Long = {
    val u = uvarint()
    (u >>> 1) ^ -(u & 1L)
  }

  def int(): Int = {
    val u = uvarint()
    if (u < 0L || u > 0xFFFFFFFFL) fail("int out of 32-bit range")
    val x = u.toInt
    (x >>> 1) ^ -(x & 1)
  }

  def float(): Float = long().toFloat / 10000.0f

  def double(): Double = long().toDouble / 10000.0

  def bool(): Boolean = byte() != 0

  /** Array element count: must be >= 0 and no larger than the bytes left. */
  def count(): Int = {
    val n = int()
    if (n < 0 || n > buf.length - pos) fail("bad array length " + n)
    n
  }

  def string(): String = {
    val n = long()
    if (n < 0L || n > (buf.length - pos).toLong) fail("bad string length " + n)
    val len = n.toInt
    val s =
      try utf8.decode(ByteBuffer.wrap(buf, pos, len)).toString
      catch { case _: CharacterCodingException => fail("invalid UTF-8") }
    pos += len
    s
  }

  def version(expected: String): Unit = {
    val v = string()
    if (v != expected) throw new BitPackerException("version mismatch: expected " + expected + ", got " + v)
  }

  def enter(): Unit = {
    depth += 1
    if (depth > 512) fail("nesting deeper than 512")
  }

  def leave(): Unit = depth -= 1
}
`
