package main

// Crystal target: one file per schema, <input>.cr, holding a module with a
// class per schema class plus a small private runtime (writer, reader,
// DecodeError). See docs/crystal.md.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func init() { registerGenerator(genCrystal, "crystal", "cr") }

var crystalKeywords = map[string]bool{
	"abstract": true, "alias": true, "annotation": true, "as": true, "asm": true, "begin": true,
	"break": true, "case": true, "class": true, "def": true, "do": true, "else": true, "elsif": true,
	"end": true, "ensure": true, "enum": true, "extend": true, "false": true, "for": true, "fun": true,
	"if": true, "in": true, "include": true, "instance_sizeof": true, "is_a": true, "lib": true,
	"macro": true, "module": true, "next": true, "nil": true, "of": true, "offsetof": true, "out": true,
	"pointerof": true, "private": true, "protected": true, "require": true, "rescue": true,
	"return": true, "select": true, "self": true, "sizeof": true, "struct": true, "super": true,
	"then": true, "true": true, "type": true, "typeof": true, "uninitialized": true, "union": true,
	"unless": true, "until": true, "verbatim": true, "when": true, "while": true, "with": true,
	"yield": true,
	// Methods the generated classes (or Object) define; a property of the
	// same name would clobber them.
	"encode": true, "encode_to": true, "decode": true, "decode_from": true, "hash": true,
	"dup": true, "clone": true, "inspect": true, "to_s": true, "object_id": true, "initialize": true,
	"allocate": true, "new": true, "tap": true, "try": true, "itself": true,
}

// Runtime type names the generated module defines; a schema class may not use them.
var crystalReserved = map[string]bool{"DecodeError": true, "BPWriter": true, "BPReader": true, "VERSION": true}

func crystalScalar(t string) (typ, zero, method string, ok bool) {
	switch t {
	case "int":
		return "Int32", "0", "int", true
	case "long":
		return "Int64", "0_i64", "long", true
	case "float":
		return "Float32", "0_f32", "float", true
	case "double":
		return "Float64", "0.0", "double", true
	case "bool":
		return "Bool", "false", "bool", true
	case "string":
		return "String", `""`, "string", true
	}
	return "", "", "", false
}

func crystalTypeName(n string) string {
	if n == "" {
		return n
	}
	return strings.ToUpper(n[:1]) + n[1:]
}

func crystalFieldName(n string) string {
	if n == "" {
		return n
	}
	n = strings.ToLower(n[:1]) + n[1:]
	if n[0] >= '0' && n[0] <= '9' {
		n = "f" + n
	}
	if crystalKeywords[n] {
		n += "_"
	}
	return n
}

// crystalModuleName turns a file stem like "bench_complex" into "BenchComplex".
func crystalModuleName(stem string) string {
	var b strings.Builder
	up := true
	for _, r := range stem {
		switch {
		case r == '_' || r == '-' || r == '.' || r == ' ':
			up = true
		case up:
			b.WriteString(strings.ToUpper(string(r)))
			up = false
		default:
			b.WriteRune(r)
		}
	}
	s := b.String()
	if s == "" || s[0] < 'A' || s[0] > 'Z' {
		s = "Schema" + s
	}
	return s
}

func genCrystal(classes []Class, cfg GeneratorConfig) error {
	module := crystalModuleName(cfg.InputFileName)
	if cfg.PackageName != "" && cfg.PackageName != "generated" {
		module = crystalModuleName(cfg.PackageName)
	}
	for _, c := range classes {
		if crystalReserved[crystalTypeName(c.Name)] {
			return fmt.Errorf("crystal: class name %q collides with a generated runtime name", c.Name)
		}
		seen := map[string]string{}
		for _, f := range c.Fields {
			n := crystalFieldName(f.Name)
			if prev, dup := seen[n]; dup {
				return fmt.Errorf("crystal: fields %s.%s and %s.%s both map to %q", c.Name, prev, c.Name, f.Name, n)
			}
			seen[n] = f.Name
		}
	}

	var b strings.Builder
	w := func(format string, a ...interface{}) { fmt.Fprintf(&b, format, a...) }

	w("# Generated by BitPacker from %s.buff (schema version %s). Do not edit.\n", cfg.InputFileName, cfg.Version)
	w("#\n# Wire format: see tools/bit-packer/cross_lang_test/edge/README.md.\n# API: see tools/bit-packer/docs/crystal.md.\n\n")
	w("module %s\n", module)
	w("  # Schema version written at the start of every message and checked by `decode`.\n")
	w("  VERSION = %q\n\n", cfg.Version)
	b.WriteString(crystalRuntime)

	for _, c := range classes {
		name := crystalTypeName(c.Name)
		w("\n  # Schema class `%s`.\n", c.Name)
		w("  class %s\n", name)
		type fi struct{ name, typ, zero string }
		var fs []fi
		for _, f := range c.Fields {
			typ, zero, _, ok := crystalScalar(f.Type)
			if !ok {
				typ, zero = crystalTypeName(f.Type), crystalTypeName(f.Type)+".new"
			}
			if f.IsArray {
				zero = "[] of " + typ
				typ = "Array(" + typ + ")"
			}
			fs = append(fs, fi{crystalFieldName(f.Name), typ, zero})
		}
		for _, f := range fs {
			w("    property %s : %s\n", f.name, f.typ)
		}
		if len(fs) > 0 {
			w("\n    def initialize(*")
			for _, f := range fs {
				w(", @%s : %s = %s", f.name, f.typ, f.zero)
			}
			w(")\n    end\n\n")
			w("    def_equals_and_hash ")
			for i, f := range fs {
				if i > 0 {
					w(", ")
				}
				w("@%s", f.name)
			}
			w("\n")
		} else {
			w("\n    def initialize\n    end\n\n    def ==(other : self) : Bool\n      true\n    end\n")
		}

		// encode
		w("\n    # Encodes this value as a complete, version-prefixed message.\n")
		w("    def encode : Bytes\n      w = BPWriter.new\n      w.string(VERSION)\n      encode_to(w)\n      w.to_slice\n    end\n")
		w("\n    # Encodes this value's fields (no version prefix) into *w*.\n    # :nodoc:\n")
		w("    def encode_to(w : BPWriter) : Nil\n")
		for i, f := range c.Fields {
			fn := fs[i].name
			_, _, m, scalar := crystalScalar(f.Type)
			if f.IsArray {
				w("      w.count(@%s.size)\n", fn)
				if scalar {
					w("      @%s.each { |e| w.%s(e) }\n", fn, m)
				} else {
					w("      @%s.each { |e| e.encode_to(w) }\n", fn)
				}
			} else if scalar {
				w("      w.%s(@%s)\n", m, fn)
			} else {
				w("      @%s.encode_to(w)\n", fn)
			}
		}
		w("    end\n")

		// decode
		w("\n    # Decodes a complete message produced by `#encode`.\n")
		w("    # Raises `DecodeError` on a wrong version prefix, truncated or malformed input.\n")
		w("    # Bytes after the message are ignored.\n")
		w("    def self.decode(data : Bytes) : self\n")
		w("      r = BPReader.new(data)\n      v = r.string\n")
		w("      raise DecodeError.new(\"version mismatch: expected #{VERSION.inspect}, got #{v.inspect}\") unless v == VERSION\n")
		w("      decode_from(r)\n    end\n")
		w("\n    # Like `.decode`, but returns `nil` instead of raising `DecodeError`.\n")
		w("    def self.decode?(data : Bytes) : self?\n      decode(data)\n    rescue DecodeError\n      nil\n    end\n")
		w("\n    # :nodoc:\n    def self.decode_from(r : BPReader) : self\n      o = new\n")
		for i, f := range c.Fields {
			fn := fs[i].name
			_, _, m, scalar := crystalScalar(f.Type)
			elem := "r." + m
			if !scalar {
				elem = crystalTypeName(f.Type) + ".decode_from(r)"
			}
			if f.IsArray {
				et, _, _, ok := crystalScalar(f.Type)
				if !ok {
					et = crystalTypeName(f.Type)
				}
				w("      o.%s = Array(%s).new(r.count) { %s }\n", fn, et, elem)
			} else {
				w("      o.%s = %s\n", fn, elem)
			}
		}
		w("      o\n    end\n  end\n")
	}
	w("end\n")

	if err := os.MkdirAll(cfg.OutDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(cfg.OutDir, cfg.InputFileName+".cr"), []byte(b.String()), 0644)
}

const crystalRuntime = `  # Raised by ` + "`decode`" + ` when the input is truncated, malformed or carries
  # a different schema version.
  class DecodeError < Exception
  end

  # :nodoc:
  class BPWriter
    def initialize
      @io = IO::Memory.new
    end

    def to_slice : Bytes
      @io.to_slice
    end

    def uvarint(v : UInt64) : Nil
      while v >= 0x80
        @io.write_byte(((v & 0x7f) | 0x80).to_u8!)
        v >>= 7
      end
      @io.write_byte(v.to_u8!)
    end

    def int(v : Int32) : Nil
      uvarint(((v << 1) ^ (v >> 31)).to_u32!.to_u64)
    end

    def long(v : Int64) : Nil
      uvarint(((v << 1) ^ (v >> 63)).to_u64!)
    end

    # float: the x10000 product is computed in single precision (Float32),
    # exactly like the Go and Java targets, then truncated toward zero.
    def float(v : Float32) : Nil
      long(fixed((v * 10000_f32).to_f64))
    end

    def double(v : Float64) : Nil
      long(fixed(v * 10000.0))
    end

    # Truncates toward zero; NaN -> 0, out of range saturates (as Java does).
    private def fixed(p : Float64) : Int64
      return 0_i64 if p.nan?
      return Int64::MAX if p >= 9223372036854775808.0
      return Int64::MIN if p <= -9223372036854775808.0
      p.to_i64!
    end

    def bool(v : Bool) : Nil
      @io.write_byte(v ? 1_u8 : 0_u8)
    end

    def string(v : String) : Nil
      long(v.bytesize.to_i64)
      @io.write(v.to_slice)
    end

    def count(n : Int) : Nil
      raise ArgumentError.new("BitPacker: array longer than Int32::MAX") if n > Int32::MAX
      int(n.to_i32)
    end
  end

  # :nodoc:
  class BPReader
    def initialize(@buf : Bytes)
      @pos = 0
    end

    def remaining : Int32
      @buf.size - @pos
    end

    def byte : UInt8
      raise DecodeError.new("unexpected end of input at byte #{@pos}") if @pos >= @buf.size
      b = @buf[@pos]
      @pos += 1
      b
    end

    def uvarint : UInt64
      result = 0_u64
      shift = 0
      loop do
        b = byte
        raise DecodeError.new("varint overflows 64 bits") if shift == 63 && b > 1
        result |= (b & 0x7f).to_u64 << shift
        return result if b < 0x80
        shift += 7
      end
    end

    def int : Int32
      u = uvarint
      raise DecodeError.new("int varint overflows 32 bits") if u > UInt32::MAX
      u32 = u.to_u32!
      ((u32 >> 1) ^ (0_u32 &- (u32 & 1))).to_i32!
    end

    def long : Int64
      u = uvarint
      ((u >> 1) ^ (0_u64 &- (u & 1))).to_i64!
    end

    def float : Float32
      long.to_f32! / 10000_f32
    end

    def double : Float64
      long.to_f64! / 10000.0
    end

    def bool : Bool
      byte != 0
    end

    def string : String
      n = long
      raise DecodeError.new("bad string length #{n} at byte #{@pos}") if n < 0 || n > remaining
      s = String.new(@buf[@pos, n.to_i32])
      @pos += n.to_i32
      raise DecodeError.new("string is not valid UTF-8") unless s.valid_encoding?
      s
    end

    # Array element count. Every element takes at least one byte, so a count
    # larger than the remaining input is rejected before anything is allocated.
    def count : Int32
      n = int
      raise DecodeError.new("bad array length #{n} at byte #{@pos}") if n < 0 || n > remaining
      n
    end
  end
`
