package main

// Erlang target: `--lang erlang` (alias `erl`).
//
// Writes <schema>.hrl (one record per class plus a version macro) and
// <schema>.erl (encode_<class>/1 -> binary(), decode_<class>/1 ->
// {ok, Record} | {error, Reason}). See docs/erlang.md.

import (
	"fmt"
	"strings"
)

func init() { registerGenerator(genErlang, "erlang", "erl") }

var erlangReserved = map[string]bool{
	"after": true, "and": true, "andalso": true, "band": true, "begin": true, "bnot": true,
	"bor": true, "bsl": true, "bsr": true, "bxor": true, "case": true, "catch": true,
	"cond": true, "div": true, "end": true, "fun": true, "if": true, "let": true, "not": true,
	"of": true, "or": true, "orelse": true, "receive": true, "rem": true, "try": true,
	"when": true, "xor": true, "maybe": true, "else": true,
}

// erlangAtom quotes an atom when it is not a plain lower-case identifier.
func erlangAtom(s string) string {
	plain := s != "" && s[0] >= 'a' && s[0] <= 'z' && !erlangReserved[s]
	for _, c := range s {
		if !(c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '_' || c == '@') {
			plain = false
		}
	}
	if plain {
		return s
	}
	return "'" + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), "'", `\'`) + "'"
}

func erlangRec(c string) string { return funclangSnake(c) }

func erlangScalarSpec(t string) string {
	switch t {
	case "int":
		return "-2147483648..2147483647"
	case "long":
		return "-9223372036854775808..9223372036854775807"
	case "float", "double":
		return "float()"
	case "bool":
		return "boolean()"
	case "string":
		return "binary()"
	}
	return ""
}

func erlangDefault(f Field) string {
	if f.IsArray {
		return "[]"
	}
	switch f.Type {
	case "int", "long":
		return "0"
	case "float", "double":
		return "0.0"
	case "bool":
		return "false"
	case "string":
		return "<<>>"
	}
	return "undefined"
}

func erlangPutFun(t string) string {
	if funclangIsScalar(t) {
		return "fun bp_put_" + t + "/1"
	}
	return "fun enc_" + erlangRec(t) + "/1"
}

func erlangGetFun(t string) string {
	if funclangIsScalar(t) {
		return "fun bp_get_" + t + "/1"
	}
	return "fun dec_" + erlangRec(t) + "/1"
}

func genErlang(classes []Class, cfg GeneratorConfig) error {
	if err := funclangCheck(classes); err != nil {
		return err
	}
	mod := funclangSnake(cfg.InputFileName)
	byName := funclangByName(classes)
	macro := strings.ToUpper(mod)
	ver := "?" + macro + "_VERSION"

	// ---- header ----
	var h strings.Builder
	fmt.Fprintf(&h, "%%%% Generated by BitPacker from %s.buff. Do not edit.\n", cfg.InputFileName)
	fmt.Fprintf(&h, "-ifndef(%s_HRL).\n-define(%s_HRL, true).\n\n", macro, macro)
	fmt.Fprintf(&h, "-define(%s_VERSION, <<\"%s\">>).\n\n", macro, cfg.Version)
	defined := map[string]bool{}
	for _, g := range funclangGroups(classes) {
		for _, c := range g {
			fmt.Fprintf(&h, "-record(%s, {", erlangAtom(erlangRec(c.Name)))
			for i, f := range c.Fields {
				if i > 0 {
					h.WriteString(",")
				}
				var spec string
				if funclangIsScalar(f.Type) {
					spec = erlangScalarSpec(f.Type)
				} else if defined[f.Type] {
					spec = "#" + erlangAtom(erlangRec(f.Type)) + "{}"
				} else {
					spec = "tuple()" // forward/self reference: record not yet defined
				}
				if f.IsArray {
					spec = "[" + spec + "]"
				} else if !funclangIsScalar(f.Type) {
					spec += " | undefined"
				}
				fmt.Fprintf(&h, "\n    %s = %s :: %s", erlangAtom(f.Name), erlangDefault(f), spec)
			}
			h.WriteString("\n}).\n\n")
			defined[c.Name] = true
		}
	}
	h.WriteString("-endif.\n")

	// ---- module ----
	var b strings.Builder
	fmt.Fprintf(&b, "%%%% Generated by BitPacker from %s.buff (schema version %s). Do not edit.\n", cfg.InputFileName, cfg.Version)
	fmt.Fprintf(&b, "-module(%s).\n\n-include(\"%s.hrl\").\n\n", erlangAtom(mod), mod)
	b.WriteString("-export([version/0")
	for _, c := range classes {
		r := erlangRec(c.Name)
		fmt.Fprintf(&b, ",\n         encode_%s/1, decode_%s/1", r, r)
	}
	b.WriteString("]).\n\n")
	fmt.Fprintf(&b, "-spec version() -> binary().\nversion() -> %s.\n\n", ver)

	for _, c := range classes {
		r := erlangRec(c.Name)
		ra := erlangAtom(r)
		fmt.Fprintf(&b, "%%%% ---- %s ----\n\n", c.Name)
		fmt.Fprintf(&b, "%%%% Encodes a #%s{} as a version-prefixed message. Raises\n", r)
		b.WriteString("%% error({bitpacker, Reason}) on a value the wire cannot carry.\n")
		fmt.Fprintf(&b, "-spec encode_%s(#%s{}) -> binary().\n", r, ra)
		fmt.Fprintf(&b, "encode_%s(Rec) ->\n    try iolist_to_binary([bp_put_string(%s), enc_%s(Rec)])\n", r, ver, r)
		b.WriteString("    catch throw:{bitpacker, Reason} -> erlang:error({bitpacker, Reason})\n    end.\n\n")
		fmt.Fprintf(&b, "-spec decode_%s(binary()) -> {ok, #%s{}} | {error, term()}.\n", r, ra)
		fmt.Fprintf(&b, "decode_%s(Bin) when is_binary(Bin) ->\n    try\n", r)
		b.WriteString("        {V, B1} = bp_get_string(Bin),\n")
		fmt.Fprintf(&b, "        V =:= %s orelse throw({bitpacker, {version_mismatch, %s, V}}),\n", ver, ver)
		fmt.Fprintf(&b, "        {Rec, _Trailing} = dec_%s(B1),\n        {ok, Rec}\n", r)
		b.WriteString("    catch throw:{bitpacker, Reason} -> {error, Reason}\n    end;\n")
		fmt.Fprintf(&b, "decode_%s(_) ->\n    {error, badarg}.\n\n", r)

		// body encoder
		fmt.Fprintf(&b, "enc_%s(undefined) ->\n    enc_%s(#%s{});\n", r, r, ra)
		if len(c.Fields) == 0 {
			fmt.Fprintf(&b, "enc_%s(#%s{}) ->\n    [].\n\n", r, ra)
		} else {
			fmt.Fprintf(&b, "enc_%s(#%s{", r, ra)
			for i, f := range c.Fields {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%s = F%d", erlangAtom(f.Name), i+1)
			}
			b.WriteString("}) ->\n    [")
			for i, f := range c.Fields {
				if i > 0 {
					b.WriteString(",\n     ")
				}
				if f.IsArray {
					fmt.Fprintf(&b, "bp_put_array(F%d, %s)", i+1, erlangPutFun(f.Type))
				} else if funclangIsScalar(f.Type) {
					fmt.Fprintf(&b, "bp_put_%s(F%d)", f.Type, i+1)
				} else {
					fmt.Fprintf(&b, "enc_%s(F%d)", erlangRec(f.Type), i+1)
				}
			}
			b.WriteString("].\n\n")
		}

		// body decoder
		fmt.Fprintf(&b, "dec_%s(B0) ->\n", r)
		for i, f := range c.Fields {
			if f.IsArray {
				min := 0
				if funclangMinOneByte(f.Type, byName, map[string]bool{}) {
					min = 1
				}
				fmt.Fprintf(&b, "    {F%d, B%d} = bp_get_array(B%d, %s, %d),\n", i+1, i+1, i, erlangGetFun(f.Type), min)
			} else if funclangIsScalar(f.Type) {
				fmt.Fprintf(&b, "    {F%d, B%d} = bp_get_%s(B%d),\n", i+1, i+1, f.Type, i)
			} else {
				fmt.Fprintf(&b, "    {F%d, B%d} = dec_%s(B%d),\n", i+1, i+1, erlangRec(f.Type), i)
			}
		}
		fmt.Fprintf(&b, "    {#%s{", ra)
		for i, f := range c.Fields {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%s = F%d", erlangAtom(f.Name), i+1)
		}
		fmt.Fprintf(&b, "}, B%d}.\n\n", len(c.Fields))
	}
	b.WriteString(erlangRuntime)
	if err := funclangWrite(cfg.OutDir, mod+".hrl", h.String()); err != nil {
		return err
	}
	return funclangWrite(cfg.OutDir, mod+".erl", b.String())
}

const erlangRuntime = `%% ---- wire runtime (see cross_lang_test/edge/README.md) ----

%% Not every schema uses every helper.
-compile(nowarn_unused_function).

-define(BP_M32, 16#FFFFFFFF).
-define(BP_M64, 16#FFFFFFFFFFFFFFFF).

bp_fail(Reason) -> throw({bitpacker, Reason}).

%% Unsigned LEB128 of a non-negative integer, as an iolist.
bp_uvarint(N) when N < 128 -> [N];
bp_uvarint(N) -> [(N band 127) bor 128 | bp_uvarint(N bsr 7)].

%% Two's-complement wrap of any (big) integer into Bits bits, then zigzag.
bp_zigzag(V, Bits, Mask) ->
    W = V band Mask,
    S = case W bsr (Bits - 1) of 0 -> W; _ -> W - (Mask + 1) end,
    ((S bsl 1) bxor (S bsr (Bits - 1))) band Mask.

bp_put_int(V) when is_integer(V) -> bp_uvarint(bp_zigzag(V, 32, ?BP_M32));
bp_put_int(V) -> bp_fail({not_an_integer, V}).

bp_put_long(V) when is_integer(V) -> bp_uvarint(bp_zigzag(V, 64, ?BP_M64));
bp_put_long(V) -> bp_fail({not_an_integer, V}).

%% Round a double to the nearest float32 (fails when out of float32 range).
bp_f32(X) ->
    case <<X:32/float>> of
        <<Y:32/float>> -> Y;
        _ -> bp_fail({float32_out_of_range, X})
    end.

%% float fields: the x10000 is done in single precision, as the float32
%% targets do: trunc(float32(float32(V) * 10000)).
bp_put_float(V) when is_number(V) ->
    F = bp_f32(try float(V) catch error:_ -> bp_fail({float32_out_of_range, V}) end),
    bp_put_fixed(bp_f32(F * 10000.0));
bp_put_float(V) -> bp_fail({not_a_number, V}).

bp_put_double(V) when is_number(V) ->
    S = try float(V) * 10000.0 catch error:_ -> bp_fail({double_out_of_range, V}) end,
    bp_put_fixed(S);
bp_put_double(V) -> bp_fail({not_a_number, V}).

bp_put_fixed(S) ->
    T = trunc(S),
    case T >= -16#8000000000000000 andalso T =< 16#7FFFFFFFFFFFFFFF of
        true -> bp_put_long(T);
        false -> bp_fail({fixed_point_out_of_range, S})
    end.

bp_put_bool(true) -> [1];
bp_put_bool(false) -> [0];
bp_put_bool(V) -> bp_fail({not_a_boolean, V}).

bp_put_string(S) when is_binary(S) -> [bp_put_long(byte_size(S)), S];
bp_put_string(S) when is_list(S) ->
    case unicode:characters_to_binary(S) of
        B when is_binary(B) -> bp_put_string(B);
        _ -> bp_fail({invalid_string, S})
    end;
bp_put_string(S) -> bp_fail({invalid_string, S}).

bp_put_array(L, Put) when is_list(L) -> [bp_put_int(length(L)) | [Put(E) || E <- L]];
bp_put_array(L, _) -> bp_fail({not_a_list, L}).

%% Decoders take a binary and return {Value, Rest}.

bp_get_uvarint(B) -> bp_get_uvarint(B, 0, 0).
bp_get_uvarint(<<1:1, V:7, Rest/binary>>, Shift, Acc) when Shift < 63 ->
    bp_get_uvarint(Rest, Shift + 7, Acc bor (V bsl Shift));
bp_get_uvarint(<<0:1, V:7, Rest/binary>>, Shift, Acc) ->
    {(Acc bor (V bsl Shift)) band ?BP_M64, Rest};
bp_get_uvarint(<<_, _/binary>>, _, _) -> bp_fail(varint_too_long);
bp_get_uvarint(<<>>, _, _) -> bp_fail(truncated).

bp_get_int(B) ->
    {U, R} = bp_get_uvarint(B),
    Z = U band ?BP_M32,
    {(Z bsr 1) bxor -(Z band 1), R}.

bp_get_long(B) ->
    {Z, R} = bp_get_uvarint(B),
    {(Z bsr 1) bxor -(Z band 1), R}.

%% Correctly rounded int64 -> float32 (a double would round twice above 2^53).
bp_int_to_f32(N) when N < (1 bsl 53), N > -(1 bsl 53) -> bp_f32(float(N));
bp_int_to_f32(N) ->
    A = abs(N),
    Y = (A bsr 11) bor (case A band 2047 of 0 -> 0; _ -> 1 end),
    F = bp_f32(float(Y) * 2048.0),
    case N < 0 of true -> -F; false -> F end.

bp_get_float(B) ->
    {N, R} = bp_get_long(B),
    {bp_f32(bp_int_to_f32(N) / 10000.0), R}.

bp_get_double(B) ->
    {N, R} = bp_get_long(B),
    {N / 10000.0, R}.

bp_get_bool(<<0, R/binary>>) -> {false, R};
bp_get_bool(<<_, R/binary>>) -> {true, R};
bp_get_bool(<<>>) -> bp_fail(truncated).

bp_get_string(B) ->
    {Len, R} = bp_get_long(B),
    Len >= 0 orelse bp_fail({negative_length, Len}),
    case R of
        <<S:Len/binary, R2/binary>> ->
            case unicode:characters_to_binary(S) of
                S -> {binary:copy(S), R2};
                _ -> bp_fail(invalid_utf8)
            end;
        _ -> bp_fail(truncated)
    end.

%% Min is 1 when every element takes at least one byte, so a count larger
%% than the bytes left is rejected before any work is done.
bp_get_array(B, Get, Min) ->
    {N, R} = bp_get_int(B),
    N >= 0 orelse bp_fail({negative_length, N}),
    (Min =:= 0 orelse N =< byte_size(R)) orelse bp_fail(truncated),
    bp_get_n(N, R, Get, []).

bp_get_n(0, R, _, Acc) -> {lists:reverse(Acc), R};
bp_get_n(N, B, Get, Acc) ->
    {V, R} = Get(B),
    bp_get_n(N - 1, R, Get, [V | Acc]).
`
