package main

// TypeScript target: `--lang typescript` (alias `ts`). Writes
// <schema>.ts: one exported interface + class per schema class, with
// encode(): Uint8Array and static decode(Uint8Array) that throws
// BitPackerError. No imports, no Node or DOM APIs (UTF-8 is hand-rolled),
// so the file works unchanged in browsers, Node, Deno and Bun. Needs an
// ES2020 target (bigint). See docs/typescript.md.

import (
	"fmt"
	"strings"
)

func init() { registerGenerator(genTypeScript, "typescript", "ts") }

var typescriptReservedMembers = map[string]bool{
	"constructor": true, "encode": true, "__proto__": true, "prototype": true,
	// Object.prototype members: a field of the same name would make every
	// object literal fail to type-check against the Fields interface.
	"toString": true, "valueOf": true, "hasOwnProperty": true, "isPrototypeOf": true,
	"propertyIsEnumerable": true, "toLocaleString": true,
}

// Class names that would shadow globals or runtime helpers the generated
// file relies on.
var typescriptReservedClasses = map[string]bool{
	"BpWriter": true, "BpReader": true, "BitPackerError": true, "VERSION": true,
	"Error": true, "Math": true, "Number": true, "BigInt": true, "String": true,
	"Uint8Array": true, "Object": true, "Array": true, "Partial": true,
}

func typescriptField(name string) string {
	n := polyglotCamel(name)
	if typescriptReservedMembers[n] {
		n += "_"
	}
	return n
}

func typescriptScalar(t string) string {
	switch t {
	case "int", "float", "double":
		return "number"
	case "long":
		return "bigint"
	case "bool":
		return "boolean"
	case "string":
		return "string"
	}
	return t
}

func typescriptDefault(f Field) string {
	if f.IsArray {
		return "[]"
	}
	switch f.Type {
	case "int", "float", "double":
		return "0"
	case "long":
		return "0n"
	case "bool":
		return "false"
	case "string":
		return `""`
	}
	return "new " + f.Type + "()"
}

func genTypeScript(classes []Class, cfg GeneratorConfig) error {
	if err := polyglotValidate("typescript", classes, typescriptField); err != nil {
		return err
	}
	for _, c := range classes {
		if typescriptReservedClasses[c.Name] || strings.HasPrefix(c.Name, "bp") {
			return fmt.Errorf("typescript: class name %s clashes with a name the generated code uses", c.Name)
		}
	}
	p := &polyglotLines{unit: "  "}
	p.line("// Generated by BitPacker from %s.buff (schema version %s). Do not edit.", cfg.InputFileName, cfg.Version)
	p.line("// Pure TypeScript (ES2020+): no imports, no Node or DOM APIs.")
	p.line("")
	p.line("/** The schema version every encoded message starts with. */")
	p.line("export const VERSION = %s;", polyglotQuote(cfg.Version))
	p.raw(typescriptRuntime)
	for _, c := range classes {
		typescriptClass(p, c)
	}
	return polyglotWrite(cfg, cfg.InputFileName+".ts", p.String())
}

func typescriptFieldType(f Field, iface bool) string {
	t := typescriptScalar(f.Type)
	if !polyglotIsScalar(f.Type) && iface {
		t = f.Type + "Fields"
	}
	if f.IsArray {
		return t + "[]"
	}
	return t
}

func typescriptWriteOne(expr, t string) string {
	if polyglotIsScalar(t) {
		return fmt.Sprintf("w.%s(%s);", t, expr)
	}
	return fmt.Sprintf("bpWrite%s(w, %s);", t, expr)
}

func typescriptReadOne(t string) string {
	if polyglotIsScalar(t) {
		return fmt.Sprintf("r.%s()", t)
	}
	return fmt.Sprintf("bpRead%s(r)", t)
}

func typescriptClass(p *polyglotLines, c Class) {
	n := c.Name
	p.line("")
	p.line("/** Plain-data shape of %s; any object of this shape can be encoded. */", n)
	p.line("export interface %sFields {", n)
	p.in()
	for _, f := range c.Fields {
		p.line("%s: %s;", typescriptField(f.Name), typescriptFieldType(f, true))
	}
	p.out()
	p.line("}")
	p.line("")
	p.line("export class %s implements %sFields {", n, n)
	p.in()
	for _, f := range c.Fields {
		p.line("%s: %s;", typescriptField(f.Name), typescriptFieldType(f, false))
	}
	p.line("")
	p.line("/** Missing fields get zero values: 0, 0n, false, \"\", [] or a default instance. */")
	initName := "init"
	if len(c.Fields) == 0 {
		initName = "_init" // unused; the underscore keeps noUnusedParameters quiet
	}
	p.line("constructor(%s: Partial<%sFields> = {}) {", initName, n)
	p.in()
	for _, f := range c.Fields {
		fn := typescriptField(f.Name)
		switch {
		case polyglotIsScalar(f.Type):
			p.line("this.%s = init.%s ?? %s;", fn, fn, typescriptDefault(f))
		case f.IsArray:
			p.line("this.%s = init.%s === undefined ? [] : init.%s.map((x) => %s.from(x));", fn, fn, fn, f.Type)
		default:
			p.line("this.%s = init.%s === undefined ? new %s() : %s.from(init.%s);", fn, fn, f.Type, f.Type, fn)
		}
	}
	p.out()
	p.line("}")
	p.line("")
	p.line("/** Returns value itself if it already is a %s, else a %s built from its fields. */", n, n)
	p.line("static from(value: %sFields): %s {", n, n)
	p.line("  return value instanceof %s ? value : new %s(value);", n, n)
	p.line("}")
	p.line("")
	p.line("/** Encodes this value as a version-prefixed BitPacker message. Throws RangeError for a NaN, infinite or out-of-range float/double. */")
	p.line("encode(): Uint8Array {")
	p.line("  return %s.encode(this);", n)
	p.line("}")
	p.line("")
	p.line("/** Encodes any %sFields-shaped object as a version-prefixed BitPacker message (RangeError as for encode()). */", n)
	p.line("static encode(value: %sFields): Uint8Array {", n)
	p.line("  const w = new BpWriter();")
	p.line("  w.string(VERSION);")
	p.line("  bpWrite%s(w, value);", n)
	p.line("  return w.finish();")
	p.line("}")
	p.line("")
	p.line("/** Decodes a version-prefixed message. Throws BitPackerError on a version mismatch or malformed/truncated input. */")
	p.line("static decode(data: Uint8Array): %s {", n)
	p.line("  const r = new BpReader(data);")
	p.line("  const version = r.string();")
	p.line("  if (version !== VERSION) {")
	p.line("    throw new BitPackerError(`version mismatch: expected ${VERSION}, got ${version}`);")
	p.line("  }")
	p.line("  return bpRead%s(r);", n)
	p.line("}")
	p.out()
	p.line("}")
	p.line("")
	p.line("function bpWrite%s(w: BpWriter, v: %sFields): void {", n, n)
	p.in()
	for _, f := range c.Fields {
		fn := typescriptField(f.Name)
		if f.IsArray {
			p.line("w.int(v.%s.length);", fn)
			p.line("for (const x of v.%s) %s", fn, typescriptWriteOne("x", f.Type))
		} else {
			p.line("%s", typescriptWriteOne("v."+fn, f.Type))
		}
	}
	if len(c.Fields) == 0 {
		p.line("void w;")
		p.line("void v;")
	}
	p.out()
	p.line("}")
	p.line("")
	p.line("function bpRead%s(r: BpReader): %s {", n, n)
	p.in()
	p.line("r.enter();")
	for i, f := range c.Fields {
		if f.IsArray {
			p.line("const n%d = r.count();", i)
			p.line("const f%d: %s = [];", i, typescriptFieldType(f, false))
			p.line("for (let i = 0; i < n%d; i++) f%d.push(%s);", i, i, typescriptReadOne(f.Type))
		} else {
			p.line("const f%d = %s;", i, typescriptReadOne(f.Type))
		}
	}
	p.line("r.leave();")
	var inits []string
	for i, f := range c.Fields {
		inits = append(inits, fmt.Sprintf("%s: f%d", typescriptField(f.Name), i))
	}
	if len(inits) == 0 {
		p.line("return new %s();", n)
	} else {
		p.line("return new %s({ %s });", n, strings.Join(inits, ", "))
	}
	p.out()
	p.line("}")
}

const typescriptRuntime = `
/** Thrown by decode() on a version mismatch or malformed/truncated input. */
export class BitPackerError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BitPackerError";
  }
}

const bpU64Mask = (1n << 64n) - 1n;
const bpTwo63 = 9223372036854775808;
const bpTwo52 = 4503599627370496;
const bpMaxDepth = 512;

/** UTF-8 byte length of s; a lone surrogate counts as U+FFFD (3 bytes). */
function bpUtf8Length(s: string): number {
  let n = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c < 0x80) n += 1;
    else if (c < 0x800) n += 2;
    else if (c >= 0xd800 && c <= 0xdbff && i + 1 < s.length && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) {
      n += 4;
      i++;
    } else n += 3;
  }
  return n;
}

class BpWriter {
  buf: Uint8Array;
  pos: number;

  constructor() {
    this.buf = new Uint8Array(256);
    this.pos = 0;
  }

  reserve(n: number): void {
    if (this.pos + n <= this.buf.length) return;
    let cap = this.buf.length * 2;
    while (cap < this.pos + n) cap *= 2;
    const next = new Uint8Array(cap);
    next.set(this.buf.subarray(0, this.pos));
    this.buf = next;
  }

  /** Unsigned LEB128 of an integer in [0, 2^53). */
  uvarNum(u: number): void {
    this.reserve(8);
    const b = this.buf;
    let p = this.pos;
    while (u >= 0x80) {
      b[p++] = (u % 0x80) | 0x80;
      u = Math.floor(u / 0x80);
    }
    b[p++] = u;
    this.pos = p;
  }

  /** Unsigned LEB128 of a bigint in [0, 2^64). */
  uvarBig(u: bigint): void {
    this.reserve(10);
    const b = this.buf;
    let p = this.pos;
    while (u >= 0x80n) {
      b[p++] = Number(u & 0x7fn) | 0x80;
      u >>= 7n;
    }
    b[p++] = Number(u);
    this.pos = p;
  }

  /** int: wrapped to 32 bits (v | 0), zigzag, varint. */
  int(v: number): void {
    const n = v | 0;
    this.uvarNum(((n << 1) ^ (n >> 31)) >>> 0);
  }

  /** long: wrapped to 64 bits (BigInt.asIntN), zigzag, varint. */
  long(v: bigint): void {
    const n = BigInt.asIntN(64, v);
    if (n > -0x10000000000000n && n < 0x10000000000000n) {
      const x = Number(n);
      this.uvarNum(x >= 0 ? x * 2 : -x * 2 - 1);
    } else {
      this.uvarBig(((n << 1n) ^ (n >> 63n)) & bpU64Mask);
    }
  }

  /** Fixed point: s is v * 10000 already computed in the field's precision,
   *  truncated toward zero. NaN, infinities and products outside the int64
   *  range are rejected with a RangeError (never saturated or wrapped). */
  fixed(s: number, kind: string, v: number): void {
    if (!(s >= -bpTwo63 && s < bpTwo63)) {
      throw new RangeError("BitPacker: " + kind + " value " + v + " is NaN, infinite or too large for fixed point (v * 10000 must fit in an int64)");
    }
    const t = Math.trunc(s);
    if (t > -bpTwo52 && t < bpTwo52) this.uvarNum(t >= 0 ? t * 2 : -t * 2 - 1);
    else this.long(BigInt(t));
  }

  /** float: v * 10000 in single precision (float32), exactly as the Go/Java targets.
   *  The product of two float32 values is exact in a double, so one Math.fround
   *  of it is the IEEE float32 multiplication. */
  float(v: number): void {
    this.fixed(Math.fround(Math.fround(v) * 10000), "float", v);
  }

  double(v: number): void {
    this.fixed(v * 10000, "double", v);
  }

  bool(v: boolean): void {
    this.reserve(1);
    this.buf[this.pos++] = v ? 1 : 0;
  }

  /** UTF-8 byte length as a long, then the bytes. Lone surrogates become U+FFFD. */
  string(v: string): void {
    const len = bpUtf8Length(v);
    this.uvarNum(len * 2);
    this.reserve(len);
    const b = this.buf;
    let p = this.pos;
    for (let i = 0; i < v.length; i++) {
      let c = v.charCodeAt(i);
      if (c < 0x80) {
        b[p++] = c;
        continue;
      }
      if (c < 0x800) {
        b[p++] = 0xc0 | (c >> 6);
        b[p++] = 0x80 | (c & 0x3f);
        continue;
      }
      if (c >= 0xd800 && c <= 0xdfff) {
        const d = i + 1 < v.length ? v.charCodeAt(i + 1) : 0;
        if (c <= 0xdbff && (d & 0xfc00) === 0xdc00) {
          const cp = 0x10000 + ((c - 0xd800) << 10) + (d - 0xdc00);
          i++;
          b[p++] = 0xf0 | (cp >> 18);
          b[p++] = 0x80 | ((cp >> 12) & 0x3f);
          b[p++] = 0x80 | ((cp >> 6) & 0x3f);
          b[p++] = 0x80 | (cp & 0x3f);
          continue;
        }
        c = 0xfffd;
      }
      b[p++] = 0xe0 | (c >> 12);
      b[p++] = 0x80 | ((c >> 6) & 0x3f);
      b[p++] = 0x80 | (c & 0x3f);
    }
    this.pos = p;
  }

  finish(): Uint8Array {
    return this.buf.slice(0, this.pos);
  }
}

class BpReader {
  buf: Uint8Array;
  pos: number;
  depth: number;

  constructor(buf: Uint8Array) {
    this.buf = buf;
    this.pos = 0;
    this.depth = 0;
  }

  fail(what: string): never {
    throw new BitPackerError(what + " at byte " + this.pos);
  }

  byte(): number {
    if (this.pos >= this.buf.length) this.fail("truncated input");
    return this.buf[this.pos++] as number;
  }

  /** Unsigned LEB128 (at most 10 bytes, 64 bits). A number when below 2^53, else a bigint. */
  uvar(): number | bigint {
    let result = 0;
    let mul = 1;
    for (let i = 0; i < 7; i++) {
      const b = this.byte();
      result += (b & 0x7f) * mul;
      if (b < 0x80) return result;
      mul *= 0x80;
    }
    let big = BigInt(result);
    let shift = 49n;
    for (let i = 7; i < 10; i++) {
      const b = this.byte();
      if (i === 9 && b > 1) this.fail("varint overflows 64 bits");
      big |= BigInt(b & 0x7f) << shift;
      if (b < 0x80) return big <= 0x1fffffffffffffn ? Number(big) : big;
      shift += 7n;
    }
    return this.fail("varint longer than 10 bytes");
  }

  /** Zigzag-decoded signed 64-bit value: a number when it is exactly representable, else a bigint. */
  sint(): number | bigint {
    const u = this.uvar();
    if (typeof u === "number") return u % 2 === 0 ? u / 2 : -(u + 1) / 2;
    return (u >> 1n) ^ -(u & 1n);
  }

  int(): number {
    const u = this.uvar();
    if (typeof u !== "number" || u > 0xffffffff) return this.fail("int out of 32-bit range");
    return (u >>> 1) ^ -(u & 1);
  }

  long(): bigint {
    const s = this.sint();
    return typeof s === "number" ? BigInt(s) : s;
  }

  float(): number {
    return Math.fround(Math.fround(Number(this.sint())) / 10000);
  }

  double(): number {
    return Number(this.sint()) / 10000;
  }

  bool(): boolean {
    return this.byte() !== 0;
  }

  /** Array element count: an int that must be >= 0 and no larger than the bytes left. */
  count(): number {
    const n = this.int();
    if (n < 0 || n > this.buf.length - this.pos) this.fail("bad array length " + n);
    return n;
  }

  string(): string {
    const s = this.sint();
    if (typeof s !== "number" || s < 0 || s > this.buf.length - this.pos) {
      return this.fail("bad string length " + String(s));
    }
    const b = this.buf;
    let p = this.pos;
    const end = p + s;
    let out = "";
    const units: number[] = [];
    while (p < end) {
      const c = b[p++] as number;
      if (c < 0x80) {
        units.push(c);
      } else {
        let cp: number;
        let need: number;
        let min: number;
        if (c >= 0xc2 && c <= 0xdf) {
          cp = c & 0x1f;
          need = 1;
          min = 0x80;
        } else if (c >= 0xe0 && c <= 0xef) {
          cp = c & 0x0f;
          need = 2;
          min = 0x800;
        } else if (c >= 0xf0 && c <= 0xf4) {
          cp = c & 0x07;
          need = 3;
          min = 0x10000;
        } else {
          this.pos = p - 1;
          return this.fail("invalid UTF-8");
        }
        if (end - p < need) {
          this.pos = p - 1;
          return this.fail("invalid UTF-8");
        }
        for (let k = 0; k < need; k++) {
          const d = b[p++] as number;
          if ((d & 0xc0) !== 0x80) {
            this.pos = p - 1;
            return this.fail("invalid UTF-8");
          }
          cp = (cp << 6) | (d & 0x3f);
        }
        if (cp < min || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) {
          this.pos = p - 1;
          return this.fail("invalid UTF-8");
        }
        if (cp >= 0x10000) {
          cp -= 0x10000;
          units.push(0xd800 + (cp >> 10), 0xdc00 + (cp & 0x3ff));
        } else {
          units.push(cp);
        }
      }
      if (units.length >= 4096) {
        out += String.fromCharCode(...units);
        units.length = 0;
      }
    }
    this.pos = end;
    return units.length > 0 ? out + String.fromCharCode(...units) : out;
  }

  enter(): void {
    if (++this.depth > bpMaxDepth) this.fail("nesting deeper than " + bpMaxDepth);
  }

  leave(): void {
    this.depth--;
  }
}
`
