package main

// Haskell target: `--lang haskell` (alias `hs`).
//
// Writes <SchemaPascal>.hs: one record type per class (fields prefixed with
// the lower-camel class name, e.g. worldStateWorldId), encode<Class> ::
// <Class> -> ByteString (via Data.ByteString.Builder), decode<Class> ::
// ByteString -> Either String <Class>, and default<Class>. Strings are
// Data.Text (the `text` package ships with GHC). See docs/haskell.md.

import (
	"fmt"
	"strings"
	"unicode"
)

func init() { registerGenerator(genHaskell, "haskell", "hs") }

func haskellTypeName(s string) string {
	p := funclangPascal(s)
	if !unicode.IsLetter([]rune(p)[0]) {
		p = "T" + p
	}
	return p
}

func haskellFieldName(class string, f Field) string {
	return funclangCamel(haskellTypeName(class)) + funclangPascal(f.Name)
}

func haskellScalar(t string) string {
	switch t {
	case "int":
		return "Int32"
	case "long":
		return "Int64"
	case "float":
		return "Float"
	case "double":
		return "Double"
	case "bool":
		return "Bool"
	case "string":
		return "T.Text"
	}
	return haskellTypeName(t)
}

func haskellDefault(f Field) string {
	if f.IsArray {
		return "[]"
	}
	switch f.Type {
	case "int", "long", "float", "double":
		return "0"
	case "bool":
		return "False"
	case "string":
		return "T.empty"
	}
	return "default" + haskellTypeName(f.Type)
}

func haskellPut(f Field, expr string) string {
	put := "bpPut"
	if funclangIsScalar(f.Type) {
		put = "bpPut" + funclangPascal(f.Type)
	}
	if f.IsArray {
		return fmt.Sprintf("bpPutList %s (%s)", put, expr)
	}
	return fmt.Sprintf("%s (%s)", put, expr)
}

func haskellGet(f Field, byName map[string]Class) string {
	get := "bpGet"
	if funclangIsScalar(f.Type) {
		get = "bpGet" + funclangPascal(f.Type)
	}
	if f.IsArray {
		min := "False"
		if funclangMinOneByte(f.Type, byName, map[string]bool{}) {
			min = "True"
		}
		return fmt.Sprintf("bpGetList %s %s", min, get)
	}
	return get
}

func genHaskell(classes []Class, cfg GeneratorConfig) error {
	if err := funclangCheck(classes); err != nil {
		return err
	}
	mod := haskellTypeName(cfg.InputFileName)
	byName := funclangByName(classes)

	var b strings.Builder
	fmt.Fprintf(&b, "-- | Generated by BitPacker from %s.buff (schema version %s). Do not edit.\n", cfg.InputFileName, cfg.Version)
	b.WriteString("{-# LANGUAGE BangPatterns #-}\n{-# OPTIONS_GHC -Wno-unused-top-binds #-}\n")
	fmt.Fprintf(&b, "module %s\n  ( schemaVersion\n  , BitPacked\n  , encodeMessage\n  , decodeMessage\n", mod)
	for _, c := range classes {
		t := haskellTypeName(c.Name)
		fmt.Fprintf(&b, "  , %s(..)\n  , encode%s\n  , decode%s\n  , default%s\n", t, t, t, t)
	}
	b.WriteString("  ) where\n\n")
	b.WriteString(haskellImports)
	fmt.Fprintf(&b, "\n-- | The schema version every message starts with.\nschemaVersion :: T.Text\nschemaVersion = T.pack %q\n", cfg.Version)

	for _, c := range classes {
		t := haskellTypeName(c.Name)
		fmt.Fprintf(&b, "\n-- ---------------------------------------------------------------- %s\n\n", c.Name)
		if len(c.Fields) == 0 {
			fmt.Fprintf(&b, "data %s = %s\n  deriving (Eq, Show)\n\n", t, t)
		} else {
			fmt.Fprintf(&b, "data %s = %s\n", t, t)
			for i, f := range c.Fields {
				lead := "  { "
				if i > 0 {
					lead = "  , "
				}
				ty := haskellScalar(f.Type)
				if f.IsArray {
					ty = "[" + ty + "]"
				}
				fmt.Fprintf(&b, "%s%s :: !%s\n", lead, haskellFieldName(c.Name, f), ty)
			}
			b.WriteString("  } deriving (Eq, Show)\n\n")
		}
		fmt.Fprintf(&b, "-- | A %s with every field zero, False, empty or default.\ndefault%s :: %s\n", t, t, t)
		if len(c.Fields) == 0 {
			fmt.Fprintf(&b, "default%s = %s\n\n", t, t)
		} else {
			fmt.Fprintf(&b, "default%s = %s\n", t, t)
			for i, f := range c.Fields {
				lead := "  { "
				if i > 0 {
					lead = "  , "
				}
				fmt.Fprintf(&b, "%s%s = %s\n", lead, haskellFieldName(c.Name, f), haskellDefault(f))
			}
			b.WriteString("  }\n\n")
		}
		fmt.Fprintf(&b, "instance BitPacked %s where\n", t)
		if len(c.Fields) == 0 {
			b.WriteString("  bpPut _ = mempty\n")
			fmt.Fprintf(&b, "  bpGet = pure %s\n\n", t)
		} else {
			b.WriteString("  bpPut v =\n")
			for i, f := range c.Fields {
				lead := "       "
				if i > 0 {
					lead = "    <> "
				}
				if i == 0 {
					lead = "    "
				}
				fmt.Fprintf(&b, "%s%s\n", lead, haskellPut(f, haskellFieldName(c.Name, f)+" v"))
			}
			fmt.Fprintf(&b, "  bpGet = %s\n", t)
			for i, f := range c.Fields {
				op := "<*>"
				if i == 0 {
					op = "<$>"
				}
				fmt.Fprintf(&b, "    %s %s\n", op, haskellGet(f, byName))
			}
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "-- | Encode as a version-prefixed message. Calls 'error' (when the result is\n-- forced) for a NaN, infinite or out-of-range float/double.\nencode%s :: %s -> B.ByteString\nencode%s = encodeMessage\n\n", t, t, t)
		fmt.Fprintf(&b, "-- | Decode a version-prefixed message; trailing bytes are ignored.\ndecode%s :: B.ByteString -> Either String %s\ndecode%s = decodeMessage\n", t, t, t)
	}
	b.WriteString(haskellRuntime)
	return funclangWrite(cfg.OutDir, mod+".hs", b.String())
}

const haskellImports = `import qualified Data.ByteString as B
import qualified Data.ByteString.Builder as BB
import qualified Data.ByteString.Lazy as BL
import qualified Data.ByteString.Unsafe as BU
import Data.Bits (shiftL, shiftR, xor, (.&.), (.|.))
import Data.Int (Int32, Int64)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import Data.Word (Word32, Word64, Word8)
import GHC.Float (float2Double)
`

const haskellRuntime = `
-- ---------------------------------------------------------------- runtime
-- Wire rules: cross_lang_test/edge/README.md.

-- | Types that have a BitPacker encoding (every generated record).
class BitPacked a where
  bpPut :: a -> BB.Builder
  bpGet :: BpParser a

-- | Encode any generated record as a version-prefixed message.
encodeMessage :: BitPacked a => a -> B.ByteString
encodeMessage v = BL.toStrict (BB.toLazyByteString (bpPutString schemaVersion <> bpPut v))

-- | Decode a version-prefixed message. Bytes after the message are ignored.
decodeMessage :: BitPacked a => B.ByteString -> Either String a
decodeMessage bs = fst <$> runBpParser p bs 0
  where
    p = do
      ver <- bpGetString
      if ver /= schemaVersion
        then bpFail ("version mismatch: expected " ++ show schemaVersion ++ ", got " ++ show ver)
        else bpGet

newtype BpParser a = BpParser { runBpParser :: B.ByteString -> Int -> Either String (a, Int) }

instance Functor BpParser where
  fmap f (BpParser p) = BpParser $ \s i -> case p s i of
    Left e -> Left e
    Right (a, j) -> Right (f a, j)

instance Applicative BpParser where
  pure a = BpParser $ \_ i -> Right (a, i)
  BpParser pf <*> BpParser pa = BpParser $ \s i -> case pf s i of
    Left e -> Left e
    Right (f, j) -> case pa s j of
      Left e -> Left e
      Right (a, k) -> Right (f a, k)

instance Monad BpParser where
  BpParser p >>= k = BpParser $ \s i -> case p s i of
    Left e -> Left e
    Right (a, j) -> runBpParser (k a) s j

bpFail :: String -> BpParser a
bpFail msg = BpParser $ \_ _ -> Left msg

bpRemaining :: BpParser Int
bpRemaining = BpParser $ \s i -> Right (B.length s - i, i)

-- encoding

bpPutUVarint :: Word64 -> BB.Builder
bpPutUVarint n
  | n < 0x80 = BB.word8 (fromIntegral n)
  | otherwise = BB.word8 (fromIntegral (n .&. 0x7f) .|. 0x80) <> bpPutUVarint (n ` + "`shiftR`" + ` 7)

bpPutInt :: Int32 -> BB.Builder
bpPutInt v = bpPutUVarint (fromIntegral (fromIntegral ((v ` + "`shiftL`" + ` 1) ` + "`xor`" + ` (v ` + "`shiftR`" + ` 31)) :: Word32))

bpPutLong :: Int64 -> BB.Builder
bpPutLong v = bpPutUVarint (fromIntegral ((v ` + "`shiftL`" + ` 1) ` + "`xor`" + ` (v ` + "`shiftR`" + ` 63)))

-- Fixed point: trunc(v * 10000) as a long. A float field multiplies in
-- single precision (Float), exactly like the float32 targets.
bpPutFixed :: Double -> BB.Builder
bpPutFixed s
  | isNaN s || s < -9.223372036854775808e18 || s >= 9.223372036854775808e18 =
      error ("BitPacker: float/double out of fixed-point range: " ++ show s)
  | otherwise = bpPutLong (truncate s)

bpPutFloat :: Float -> BB.Builder
bpPutFloat v = bpPutFixed (float2Double (v * 10000))

bpPutDouble :: Double -> BB.Builder
bpPutDouble v = bpPutFixed (v * 10000)

bpPutBool :: Bool -> BB.Builder
bpPutBool b = BB.word8 (if b then 1 else 0)

bpPutString :: T.Text -> BB.Builder
bpPutString t = bpPutLong (fromIntegral (B.length bs)) <> BB.byteString bs
  where bs = TE.encodeUtf8 t

bpPutList :: (a -> BB.Builder) -> [a] -> BB.Builder
bpPutList put xs = bpPutInt (fromIntegral (length xs)) <> foldMap put xs

-- decoding

bpByte :: BpParser Word8
bpByte = BpParser $ \s i ->
  if i < B.length s then Right (BU.unsafeIndex s i, i + 1) else Left "truncated"

bpGetUVarint :: BpParser Word64
bpGetUVarint = go 0 0
  where
    go :: Int -> Word64 -> BpParser Word64
    go !shift !acc = do
      b <- bpByte
      let acc' = acc .|. (fromIntegral (b .&. 0x7f) ` + "`shiftL`" + ` shift)
      if b .&. 0x80 == 0
        then return acc'
        else if shift >= 63 then bpFail "varint too long" else go (shift + 7) acc'

bpGetInt :: BpParser Int32
bpGetInt = do
  u <- bpGetUVarint
  let z = fromIntegral u :: Word32
  return (fromIntegral (z ` + "`shiftR`" + ` 1) ` + "`xor`" + ` negate (fromIntegral (z .&. 1)))

bpGetLong :: BpParser Int64
bpGetLong = do
  z <- bpGetUVarint
  return (fromIntegral (z ` + "`shiftR`" + ` 1) ` + "`xor`" + ` negate (fromIntegral (z .&. 1)))

bpGetFloat :: BpParser Float
bpGetFloat = do
  n <- bpGetLong
  return (fromIntegral n / 10000)

bpGetDouble :: BpParser Double
bpGetDouble = do
  n <- bpGetLong
  return (fromIntegral n / 10000)

bpGetBool :: BpParser Bool
bpGetBool = (/= 0) <$> bpByte

bpGetString :: BpParser T.Text
bpGetString = do
  n <- bpGetLong
  BpParser $ \s i ->
    if n < 0
      then Left "negative string length"
      else if n > fromIntegral (B.length s - i)
        then Left "truncated"
        else
          let len = fromIntegral n
          in case TE.decodeUtf8' (B.take len (B.drop i s)) of
               Left _ -> Left "invalid UTF-8"
               Right t -> Right (t, i + len)

-- minOne: every element takes at least one byte, so a count larger than the
-- bytes left is rejected before any element is read.
bpGetList :: Bool -> BpParser a -> BpParser [a]
bpGetList minOne p = do
  n <- bpGetInt
  left <- bpRemaining
  if n < 0
    then bpFail "negative array length"
    else if minOne && fromIntegral n > left
      then bpFail "truncated"
      else go (fromIntegral n :: Int) []
  where
    go 0 acc = return (reverse acc)
    go k acc = do
      x <- p
      go (k - 1) (x : acc)
`
